set(target x86_64-none-linux-gnu)
set(tool_prefix "")
set(CMAKE_SYSROOT /)
set(CMAKE_AR ${tool_prefix}ar)
set(CMAKE_ASM_COMPILER_TARGET ${target})
set(CMAKE_C_COMPILER ${tool_prefix}gcc)
set(CMAKE_C_COMPILER_TARGET ${target})
set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN /usr)
set(CMAKE_CXX_COMPILER ${tool_prefix}g++)
set(CMAKE_CXX_COMPILER_TARGET ${target})
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN /usr)
set(CMAKE_NM ${tool_prefix}nm)
set(CMAKE_RANLIB ${tool_prefix}ranlib)

