#!/usr/bin/env sh

set -xe

# Downloading PHP
PHP_TAR_FILE=php.tar.gz
apk add --no-cache --virtual .php-build-deps \
    autoconf \
    bison \
    ca-certificates \
    coreutils \
    re2c \
    wget

mkdir -p $PHP_SRC_DIR
cd $SRC_DIR
wget -O "${PHP_TAR_FILE}" "$PHP_URL"
sha256sum "${PHP_TAR_FILE}"
echo "$PHP_SHA256 *${PHP_TAR_FILE}" | sha256sum -c -
docker-php-source extract
cd $PHP_SRC_DIR

CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS"
PHP_CONFIG_ARGS=""

PHP_72_API='20170718'
PHP_74_API='20190902'
if [ "${PHP_API}" -lt "${PHP_72_API}" ] ; then
    # Removed in v7.2
    PHP_CONFIG_ARGS="--with-mcrypt $PHP_CONFIG_ARGS"
else
    PHP_CONFIG_ARGS="--with-sodium=shared $PHP_CONFIG_ARGS"
fi

if [ "${PHP_API}" -ge "${PHP_74_API}" ] ; then
    PHP_CONFIG_ARGS="--with-ffi $PHP_CONFIG_ARGS"
fi

srcdir="$PWD"
# Installing PHP
mkdir -vp /tmp/build-php
cd /tmp/build-php
"$srcdir/configure" \
    --prefix="${PHP_INSTALL_DIR}" \
    --with-config-file-path="${PHP_INI_DIR}" \
    --with-config-file-scan-dir="${PHP_INI_DIR}/conf.d" \
    --with-mhash \
    --enable-ftp \
    --enable-mbstring \
    --with-curl \
    --with-libedit \
    --without-pdo-sqlite \
    --without-sqlite3 \
    $([ -n "$SSL_DEV_DEP" ] && echo --with-openssl || echo --without-openssl ) \
    --with-zlib \
    --enable-fpm \
    --with-fpm-user=www-data \
    --with-fpm-group=www-data \
    ${PHP_CONFIG_ARGS}
make -j "$(nproc)"
make install clean
cd -
rm -fr /tmp/build-php

# Removing sources and unused packages
docker-php-source delete
rm "$SRC_DIR/${PHP_TAR_FILE}"
apk del .php-build-deps
