version: '3'

services:
  base-php5:
    image: 'datadog/dd-trace-ci:php5_centos-6'
    build:
      context: .

  php-5.4:
    build:
      context: .
      dockerfile: Dockerfile_php5
      args:
        phpVersion: 5.4
        phpTarGzUrl: https://www.php.net/distributions/php-5.4.45.tar.gz
        phpSha256Hash: 25bc4723955f4e352935258002af14a14a9810b491a19400d76fcdfa9d04b28f
    image: 'datadog/dd-trace-ci:php-5.4_centos-6'

  php-5.5:
    build:
      context: .
      dockerfile: Dockerfile_php5
      args:
        phpVersion: 5.5
        phpTarGzUrl: https://www.php.net/distributions/php-5.5.38.tar.gz
        phpSha256Hash: 4f458c9b504269615715a62f182b7c2f89bb8284f484befc221b56a1571b506e
    image: 'datadog/dd-trace-ci:php-5.5_centos-6'

  php-5.6:
    build:
      context: .
      dockerfile: Dockerfile_php5
      args:
        phpVersion: 5.6
        phpTarGzUrl: https://www.php.net/distributions/php-5.6.40.tar.gz
        phpSha256Hash: 56fb9878d12fdd921f6a0897e919f4e980d930160e154cbde2cc6d9206a27cac
    image: 'datadog/dd-trace-ci:php-5.6_centos-6'
