<?php

function start_file($integration)
{
    $autogeneratedFilePath = _get_autogenerated_file_path($integration);
    $templateFilePath = _get_template_file_path($integration);
    if (file_exists($autogeneratedFilePath)) {
        unlink($autogeneratedFilePath);
    }

    _append($integration, "<?php");
    _append($integration);
    _append($integration);
    _append($integration, "use DDTrace\SpanData;");
    _append($integration);
    _append($integration);
    _append($integration, "// This file is autogenerate from $templateFilePath");
    _append($integration);
}

function export_tracing_function($integration, $name, $defaultParams = [], $params = [])
{
    $func = new \ReflectionFunction($name);
    $filename = $func->getFileName();
    $start_line = $func->getStartLine() + 1; // '{' must be on new line
    $end_line = $func->getEndLine() - 1; // '}' must be on new line
    $length = $end_line - $start_line;

    $source = file($filename);
    $body = implode("", array_slice($source, $start_line, $length));
    $body = trim($body, " \n");

    $params = array_merge($defaultParams, $params);
    foreach ($params as $param => $value) {
        $findSingleQuote = "'[param::$param]'";
        $findDoubleQuote = "\"[param::$param]\"";
        if (is_bool($value)) {
            $replace = $value ? 'true' : 'false';
        } elseif (is_string($value)) {
            $replace = "'$value'";
        } elseif (is_numeric($value)) {
            $replace = "$value";
        }
        $body = str_replace($findSingleQuote, $replace, $body);
        $body = str_replace($findDoubleQuote, $replace, $body);
    }

    _append($integration);
    _append($integration, $body);
    _append($integration);

    return $body;
}

function export_raw_function($integration, $name)
{
    $func = new \ReflectionFunction($name);
    $filename = $func->getFileName();
    $start_line = $func->getStartLine() - 1; // '{' must be on new line
    $end_line = $func->getEndLine(); // '}' must be on new line
    $length = $end_line - $start_line;

    $source = file($filename);
    $body = implode("", array_slice($source, $start_line, $length));
    $body = trim($body, "; ");

    _append($integration);
    _append($integration, $body);
    _append($integration);

    return $body;
}

function _get_autogenerated_file_path($integration)
{
    return __DIR__ . '/' . $integration . '/' . $integration . '.autogenerated.php';
}

function _append($integration, $text = "\n")
{
    $file = _get_autogenerated_file_path($integration);
    $handle = fopen($file, 'a');
    fwrite($handle, $text);
    fclose($handle);
}

function _get_template_file_path($integration)
{
    return __DIR__ . '/' . $integration . '/' . $integration . '.template.php';
}
