#!/bin/sh
set -e

phpVersion=$1

if [ -z "${phpVersion}" ] || [ ! -f /opt/php/${phpVersion}/bin/php ]; then
    echo "Invalid PHP version. Valid versions are:"
    ls /opt/php
    exit 1
fi

sudo ln -sf /opt/php/${phpVersion}/bin/pear /usr/local/bin/pear
sudo ln -sf /opt/php/${phpVersion}/bin/pecl /usr/local/bin/pecl
sudo ln -sf /opt/php/${phpVersion}/bin/phar.phar /usr/local/bin/phar
sudo ln -sf /opt/php/${phpVersion}/bin/php /usr/local/bin/php
sudo ln -sf /opt/php/${phpVersion}/bin/php-cgi /usr/local/bin/php-cgi
sudo ln -sf /opt/php/${phpVersion}/bin/php-config /usr/local/bin/php-config
sudo ln -sf /opt/php/${phpVersion}/bin/phpdbg /usr/local/bin/phpdbg
sudo ln -sf /opt/php/${phpVersion}/bin/phpize /usr/local/bin/phpize
sudo ln -sf /opt/php/${phpVersion}/sbin/php-fpm /usr/local/bin/php-fpm
sudo ln -sf /opt/php/${phpVersion}/lib/libphp.so /usr/lib/libphp.so
sudo ln -sf /opt/php/${phpVersion}/bin/frankenphp /usr/local/bin/frankenphp
if [ "${phpVersion}" != *asan* ]; then
    sudo ln -sf /opt/php/${phpVersion}/lib/apache2handler-libphp.so /usr/lib/apache2/modules/libphp.so
fi