helper_mgr_acquire_conn run
bool(true)

Connected?
bool(true)

Contents of helper log:
[%s] pre-exec: Going for second fork
[%s] pre-exec: Intermediate process exiting
[%s] pre-exec: About to call execv
Checking open file descriptors
* has file descriptor 0
* has file descriptor 1
* has file descriptor 2
Checking procmask
array (
)
Checking umask
0
Checking parent uid (should be 1)
1
Checking process group id == pid (is a process group leader)
OK
Checking session id == pid (is a session leader)
OK

Checking socket id
file descriptor is %d
opened fd %d

Accepting a connection:
accepted a new connection
read initial message from extension (size %d)
read remaining data