//! The C API (`shm_gen_cache.h`, generated by cbindgen).
//!
//! Allocate a cache in an anonymous shared mapping, or initialise one in
//! caller-provided memory (with its size query); free it; register and
//! unregister a participant; look up and insert.
//!
//! The process- and thread-safety contract is documented on [`FfiCache`]
//! and [`FfiParticipant`], whose docs cbindgen emits into the header.

use core::ffi::c_void;
use core::ptr::NonNull;
use core::sync::atomic::AtomicU32;
use core::sync::atomic::Ordering::Relaxed;
use std::boxed::Box;

use crate::cache::Cache;
use crate::config::{Config, Derived, Params, RuntimeParams};
use crate::error::Error;
use crate::lock::ParticipantLock;
use crate::occupancy::{Estimated, Exact};

/// Status codes. The numeric values are stable API (2-15 are errors).
#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Status {
    /// Success (lookup: hit).
    Ok = 0,
    /// Lookup: the key is not cached.
    Miss = 1,
    /// Lookup: the value does not fit the output capacity.
    InsufficientCapacity = 2,
    /// The key is longer than the configured maximum.
    KeyTooLarge = 3,
    /// The value is longer than the configured maximum.
    ValueTooLarge = 4,
    /// Not returned by this API.
    InvalidMapping = 5,
    /// Every participant slot is taken by a live registration.
    ParticipantRegistryFull = 6,
    /// Not returned by this API.
    FullRetry = 7,
    /// Null/misaligned arguments, invalid configuration, overlapping
    /// buffers, or a participant inherited across fork().
    InvalidArgument = 8,
    /// A system call failed (mmap/VirtualAlloc, or the liveness backend's
    /// membarrier or thread wait).
    IoError = 9,
    /// Unsupported platform or kernel feature.
    Unsupported = 10,
    /// Internal race; not returned by lookup/insert.
    ConcurrentOperation = 11,
    /// A participant slot was corrupted.
    Corrupt = 12,
    /// The mapping is not cache-line aligned.
    Misaligned = 13,
    /// The rotation owner stayed busy (and alive) through the wait budget.
    RotationOwnerTimeout = 14,
    /// A live participant pinned to the arena being reused did not unpin in
    /// time.
    ArenaReuseTimeout = 15,
}

impl From<Error> for Status {
    #[inline(always)]
    fn from(e: Error) -> Self {
        match e {
            Error::InsufficientCapacity => Status::InsufficientCapacity,
            Error::KeyTooLarge => Status::KeyTooLarge,
            Error::ValueTooLarge => Status::ValueTooLarge,
            Error::ParticipantRegistryFull => Status::ParticipantRegistryFull,
            Error::InvalidArgument => Status::InvalidArgument,
            Error::IoError => Status::IoError,
            Error::Unsupported => Status::Unsupported,
            Error::ConcurrentOperation => Status::ConcurrentOperation,
            Error::Corrupt => Status::Corrupt,
            Error::Misaligned => Status::Misaligned,
            Error::RotationOwnerTimeout => Status::RotationOwnerTimeout,
            Error::ArenaReuseTimeout => Status::ArenaReuseTimeout,
        }
    }
}

// 'static: the parameters live in the FfiCache's heap allocation, which by
// contract outlives every participant handle.
type EstimatedParams = RuntimeParams<'static, Estimated>;
type ExactParams = RuntimeParams<'static, Exact>;

/// The two monomorphisations of the cache code (the occupancy mode is a
/// type: it changes the arena layout).
enum CacheKind {
    Estimated(Cache<'static, EstimatedParams>),
    Exact(Cache<'static, ExactParams>),
}

/// A process-local cache handle (C `ddog_sgc_Cache`, opaque).
///
/// Usage model: `ddog_sgc_cache_new` once, in the parent before forking;
/// each thread of each process registers a participant
/// (`ddog_sgc_participant_register`), uses it for lookups and inserts, and
/// unregisters it; `ddog_sgc_cache_free` once no participant of the process
/// is registered.
///
/// Process safety: any number of processes sharing the mapping (fork()ed
/// after `ddog_sgc_cache_new`) may operate concurrently. On Linux they must
/// share PID and time namespaces, with `/proc` mounted for them (the
/// liveness backend identifies participants by kernel TID and start time).
/// On Windows, which has no fork(), only the threads of one process share a
/// cache (the liveness backend identifies participants by thread ID and
/// creation time). A mapping must never be reused across boots. Other
/// platforms use a no-op liveness backend (dead participants are never
/// reaped): development only.
///
/// A `ddog_sgc_Cache` may be used from any thread for registration.
///
/// No call blocks indefinitely: waits are bounded (5 ms of wall-clock time
/// each) and end in the `*_TIMEOUT` statuses. A process that dies
/// registered (even mid-insert) is recovered by slot reaping; until its slot
/// is reaped, its pin can delay arena reuse.
pub struct FfiCache {
    kind: CacheKind,
    base: NonNull<u8>,
    len: usize,
    owns_mapping: bool,
    /// The parameters the views in `kind` point to (`Box::into_raw`).
    derived: NonNull<Derived>,
}

enum ParticipantKind {
    Estimated(ParticipantLock<'static, EstimatedParams>),
    Exact(ParticipantLock<'static, ExactParams>),
}

// Cache-line aligned, so each handle's heap allocation sits alone on its
// lines: every insert writes the occupancy estimator inside it, and handles
// of different threads sharing a line ping-pong it between cores (measured:
// -30% on 8-thread insert-heavy benches on Apple M).
/// A process-local participant handle (C `ddog_sgc_Participant`, opaque).
///
/// Thread safety: a participant belongs to the thread that registered it:
/// lookup, insert and unregister only from that thread, never concurrently,
/// and never from a signal handler.
///
/// Fork: in a fork()ed child an inherited participant is unusable (lookup
/// and insert return `DDOG_SGC_STATUS_INVALID_ARGUMENT`; unregister only
/// frees the handle); the child must register its own.
#[cfg_attr(target_arch = "aarch64", repr(align(128)))]
#[cfg_attr(not(target_arch = "aarch64"), repr(align(64)))]
pub struct FfiParticipant {
    kind: ParticipantKind,
    /// [`FORK_GENERATION`] at registration.
    fork_generation: u32,
}

impl FfiParticipant {
    /// Whether this handle was inherited from the parent across fork().
    #[inline(always)]
    fn is_inherited(&self) -> bool {
        self.fork_generation != FORK_GENERATION.load(Relaxed)
    }
}

/// Incremented in every fork()ed child (pthread_atfork), so handles
/// inherited from the parent can be recognised: their slot belongs to the
/// parent's thread.
static FORK_GENERATION: AtomicU32 = AtomicU32::new(0);

#[cfg(unix)]
extern "C" fn after_fork_in_child() {
    FORK_GENERATION.fetch_add(1, Relaxed);
}

/// Installs `after_fork_in_child` (Unix only) once per process. A failure
/// (ENOMEM) is remembered and reported on every call: without the handler,
/// inherited participants would go undetected in fork()ed children.
fn install_fork_handler() -> Result<(), Error> {
    static INSTALLED: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    let installed = *INSTALLED.get_or_init(|| {
        #[cfg(unix)]
        // SAFETY: registering a handler that only touches an atomic.
        let ok = unsafe { libc::pthread_atfork(None, None, Some(after_fork_in_child)) } == 0;
        #[cfg(not(unix))]
        let ok = true;
        ok
    });
    if installed {
        Ok(())
    } else {
        Err(Error::IoError)
    }
}

/// Builds the handle for a mapping initialised at `base`.
///
/// # Safety
/// `base..base + len` must be zero-filled, valid until the handle is freed.
unsafe fn init_in(
    base: NonNull<u8>,
    len: usize,
    derived: Derived,
    owns_mapping: bool,
) -> Result<Box<FfiCache>, Error> {
    // Before anything is built: a cache without fork detection is not
    // handed out.
    install_fork_handler()?;
    let derived_ptr = NonNull::from(Box::leak(Box::new(derived)));
    // SAFETY: freed only by ddog_sgc_cache_free (or below), after every
    // participant (contract).
    let params: &'static Derived = unsafe { derived_ptr.as_ref() };
    let kind = if params.estimates_occupancy {
        EstimatedParams::new(params)
            // SAFETY: forwarded from the caller.
            .and_then(|params| unsafe { Cache::initialize(base.as_ptr(), len, params) })
            .map(CacheKind::Estimated)
    } else {
        ExactParams::new(params)
            // SAFETY: forwarded from the caller.
            .and_then(|params| unsafe { Cache::initialize(base.as_ptr(), len, params) })
            .map(CacheKind::Exact)
    };
    match kind {
        Ok(kind) => Ok(Box::new(FfiCache {
            kind,
            base,
            len,
            owns_mapping,
            derived: derived_ptr,
        })),
        Err(e) => {
            // SAFETY: nothing references the parameters.
            drop(unsafe { Box::from_raw(derived_ptr.as_ptr()) });
            Err(e)
        }
    }
}

/// `*config` resolved; `None` if `config` is null or invalid.
///
/// # Safety
/// `config` must be null or point to a valid config.
unsafe fn resolve_config(config: *const Config) -> Option<Derived> {
    if config.is_null() {
        return None;
    }
    // SAFETY: non-null, valid per the contract.
    unsafe { config.read() }.resolve().ok()
}

/// Allocates and initialises a cache.
///
/// Validates `*config` (`DDOG_SGC_STATUS_INVALID_ARGUMENT` on any violation
/// of the configuration rules documented on `ddog_sgc_Config`), maps the
/// cache's size `MAP_SHARED | MAP_ANONYMOUS` (zero-filled, page-aligned,
/// inherited by fork()ed children together with the handle), initialises it
/// in place and stores a process-local handle in `*out`. On Windows, which
/// has no fork(), the memory is `VirtualAlloc`ed and private to the
/// process.
///
/// On Linux the mapping is advised `MADV_HUGEPAGE` before initialisation.
/// It is backed by 2 MiB pages only if
/// `/sys/kernel/mm/transparent_hugepage/shmem_enabled` allows it (`advise`,
/// `always` or `within_size`; not `never`), and pages the kernel cannot
/// allocate huge stay 4 KiB (`ShmemPmdMapped` in `/proc/PID/smaps` shows
/// how much is huge).
///
/// Errors: `INVALID_ARGUMENT` (null arguments, invalid configuration),
/// `IO_ERROR` (mmap, VirtualAlloc or pthread_atfork failed), `UNSUPPORTED`
/// (neither Unix nor Windows). `*out` is untouched on error.
///
/// # Safety
/// `config` must be null or point to a valid config; `out` must be null or
/// valid for a pointer write.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_cache_new(
    config: *const Config,
    out: *mut *mut FfiCache,
) -> Status {
    if out.is_null() {
        return Status::InvalidArgument;
    }
    // SAFETY: forwarded from the caller.
    let Some(derived) = (unsafe { resolve_config(config) }) else {
        return Status::InvalidArgument;
    };
    #[cfg(unix)]
    {
        let len = derived.mapping_size;
        // SAFETY: a fresh anonymous mapping.
        let mem = unsafe {
            libc::mmap(
                core::ptr::null_mut(),
                len,
                libc::PROT_READ | libc::PROT_WRITE,
                libc::MAP_SHARED | libc::MAP_ANONYMOUS,
                -1,
                0,
            )
        };
        if mem == libc::MAP_FAILED {
            return Status::IoError;
        }
        let Some(base) = NonNull::new(mem.cast::<u8>()) else {
            return Status::IoError;
        };
        // Lookups touch random index buckets and records all over the
        // mapping, so its TLB footprint is the whole mapping. Ask for
        // transparent huge pages before initialisation faults the pages in.
        // Best effort: the advice only takes effect when shmem THP is
        // enabled (`shmem_enabled` advise, always or within_size), and a
        // failure (e.g. a kernel without THP) leaves 4 KiB pages.
        #[cfg(target_os = "linux")]
        // SAFETY: advice on the mapping created above.
        unsafe {
            libc::madvise(mem, len, libc::MADV_HUGEPAGE);
        }
        // SAFETY: the mapping is zero-filled and lives until cache_free.
        match unsafe { init_in(base, len, derived, true) } {
            Ok(handle) => {
                // SAFETY: out is valid (checked non-null, contract).
                unsafe { out.write(Box::into_raw(handle)) };
                Status::Ok
            }
            Err(e) => {
                // SAFETY: unmapping the mapping created above.
                unsafe { libc::munmap(mem, len) };
                e.into()
            }
        }
    }
    #[cfg(windows)]
    {
        use windows_sys::Win32::System::Memory::{
            MEM_COMMIT, MEM_RESERVE, PAGE_READWRITE, VirtualAlloc,
        };
        let len = derived.mapping_size;
        // SAFETY: a fresh allocation (zero-filled, 64 KiB-aligned).
        let mem = unsafe {
            VirtualAlloc(
                core::ptr::null(),
                len,
                MEM_RESERVE | MEM_COMMIT,
                PAGE_READWRITE,
            )
        };
        let Some(base) = NonNull::new(mem.cast::<u8>()) else {
            return Status::IoError;
        };
        // SAFETY: the memory is zero-filled and lives until cache_free.
        match unsafe { init_in(base, len, derived, true) } {
            Ok(handle) => {
                // SAFETY: out is valid (checked non-null, contract).
                unsafe { out.write(Box::into_raw(handle)) };
                Status::Ok
            }
            Err(e) => {
                // SAFETY: releasing the allocation made above.
                unsafe { release_allocation(mem) };
                e.into()
            }
        }
    }
    #[cfg(not(any(unix, windows)))]
    {
        let _ = derived;
        Status::Unsupported
    }
}

/// Releases memory from `VirtualAlloc` in `ddog_sgc_cache_new`.
///
/// # Safety
/// `mem` must be that allocation's base, and nothing may reference it.
#[cfg(windows)]
unsafe fn release_allocation(mem: *mut c_void) {
    use windows_sys::Win32::System::Memory::{MEM_RELEASE, VirtualFree};
    // SAFETY: forwarded from the caller; MEM_RELEASE takes size zero.
    unsafe { VirtualFree(mem, 0, MEM_RELEASE) };
}

/// Frees the handle and, for a cache from `ddog_sgc_cache_new`, unmaps this
/// process's view of it (other processes keep their mappings; memory given
/// to `ddog_sgc_cache_init_in` stays the caller's). NULL is a no-op.
///
/// # Safety
/// `cache` must be null or a handle from `ddog_sgc_cache_new` or
/// `ddog_sgc_cache_init_in` not yet freed, and no participant of this
/// process may still be registered with it (participant handles borrow the
/// mapping).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_cache_free(cache: *mut FfiCache) {
    if cache.is_null() {
        return;
    }
    // SAFETY: a handle from Box::into_raw (contract).
    let cache = unsafe { Box::from_raw(cache) };
    #[cfg(unix)]
    if cache.owns_mapping {
        // SAFETY: the mapping created by cache_new; nothing borrows it any
        // longer (contract).
        unsafe { libc::munmap(cache.base.as_ptr().cast::<c_void>(), cache.len) };
    }
    #[cfg(windows)]
    if cache.owns_mapping {
        // SAFETY: the allocation made by cache_new; nothing borrows it any
        // longer (contract).
        unsafe { release_allocation(cache.base.as_ptr().cast::<c_void>()) };
    }
    #[cfg(not(unix))]
    let _ = cache.len;
    #[cfg(not(any(unix, windows)))]
    let _ = (cache.base, cache.owns_mapping);
    // SAFETY: from Box::leak in init_in; the views referencing it are gone.
    drop(unsafe { Box::from_raw(cache.derived.as_ptr()) });
}

/// Claims a participant slot for the calling thread, reaping a dead
/// participant's slot when the registry is full, and stores a process-local
/// handle in `*out`.
///
/// Errors: `PARTICIPANT_REGISTRY_FULL`; `IO_ERROR` / `UNSUPPORTED` (liveness
/// backend, during slot reaping); `CORRUPT`; `INVALID_ARGUMENT` (null
/// arguments). `*out` is untouched on error.
///
/// # Safety
/// `cache` must be null or a live handle; `out` null or valid for a pointer
/// write.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_participant_register(
    cache: *const FfiCache,
    out: *mut *mut FfiParticipant,
) -> Status {
    if cache.is_null() || out.is_null() {
        return Status::InvalidArgument;
    }
    // SAFETY: a live handle (contract).
    let cache = unsafe { &*cache };
    let kind = match &cache.kind {
        CacheKind::Estimated(c) => c.register_participant().map(ParticipantKind::Estimated),
        CacheKind::Exact(c) => c.register_participant().map(ParticipantKind::Exact),
    };
    match kind {
        Ok(kind) => {
            let participant = Box::new(FfiParticipant {
                kind,
                fork_generation: FORK_GENERATION.load(Relaxed),
            });
            // SAFETY: out is valid (contract).
            unsafe { out.write(Box::into_raw(participant)) };
            Status::Ok
        }
        Err(e) => e.into(),
    }
}

/// Releases the participant's slot and frees the handle. Must
/// be called on the registering thread; aborts the process if the slot's
/// state was corrupted. In a fork()ed child of the registering process it
/// only frees the handle (the slot belongs to the parent's thread). NULL is
/// a no-op.
///
/// # Safety
/// `participant` must be null or a live handle from
/// `ddog_sgc_participant_register`, whose cache is still allocated.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_participant_unregister(participant: *mut FfiParticipant) {
    if participant.is_null() {
        return;
    }
    // SAFETY: a handle from Box::into_raw (contract).
    let participant = *unsafe { Box::from_raw(participant) };
    if participant.is_inherited() {
        core::mem::forget(participant.kind);
        return;
    }
    drop(participant); // releases the slot
}

/// Looks `key` up.
///
/// * Hit: `OK`; `*value_len` is the value's length and the value is in the
///   first `*value_len` bytes of `out_words`.
/// * Miss: `MISS`.
/// * A hit larger than `out_capacity`: `INSUFFICIENT_CAPACITY`.
/// * `key_len` above the configured maximum: `KEY_TOO_LARGE` (checked
///   first, before any pointer is used).
/// * Called in a fork()ed child of the registering process, null
///   `value_len`, null or misaligned `out_words` with a non-zero capacity,
///   or `key` overlapping the output storage: `INVALID_ARGUMENT`.
///
/// `out_words` must be 8-byte aligned with room for `ceil(out_capacity / 8)`
/// words: whole words are copied. `value_len` must not point into that
/// storage: the length is written after the value. `key` may be NULL iff
/// `key_len == 0`.
/// `out_words` contents are unspecified unless `OK`; `*value_len` is written
/// only on `OK`. A hit in the previous generation is promoted (inserted into
/// the current one); a promotion error is returned instead of `OK`
/// (`ROTATION_OWNER_TIMEOUT`, `ARENA_REUSE_TIMEOUT`, `IO_ERROR`, ...).
///
/// # Safety
/// `participant` must be a live handle used on its registering thread;
/// `key` valid for `key_len` bytes; `out_words` valid for
/// `ceil(out_capacity / 8)` words; `value_len` valid for a write and
/// outside those words.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_lookup(
    participant: *mut FfiParticipant,
    hash: u64,
    key: *const u8,
    key_len: usize,
    out_words: *mut u64,
    out_capacity: usize,
    value_len: *mut usize,
) -> Status {
    // SAFETY: a live handle (contract).
    let participant = unsafe { &mut *participant };
    if participant.is_inherited() {
        return Status::InvalidArgument;
    }
    // SAFETY: forwarded from the caller.
    unsafe {
        match &mut participant.kind {
            ParticipantKind::Estimated(lock) => {
                lookup_in(lock, hash, key, key_len, out_words, out_capacity, value_len)
            }
            ParticipantKind::Exact(lock) => {
                lookup_in(lock, hash, key, key_len, out_words, out_capacity, value_len)
            }
        }
    }
}

/// Inserts or replaces `key` -> `value`.
///
/// Returns `OK`, or `KEY_TOO_LARGE` / `VALUE_TOO_LARGE` (checked before any
/// pointer is used), `ROTATION_OWNER_TIMEOUT`, `ARENA_REUSE_TIMEOUT`,
/// `IO_ERROR`, `UNSUPPORTED`, `CORRUPT`, or `INVALID_ARGUMENT` in a fork()ed
/// child of the registering process. NULL pointers are allowed only with
/// zero lengths. Use the same hash for a key in every process.
///
/// # Safety
/// `participant` must be a live handle used on its registering thread;
/// `key` and `value` valid for their lengths.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_insert(
    participant: *mut FfiParticipant,
    hash: u64,
    key: *const u8,
    key_len: usize,
    value: *const u8,
    value_len: usize,
) -> Status {
    // SAFETY: a live handle (contract).
    let participant = unsafe { &mut *participant };
    if participant.is_inherited() {
        return Status::InvalidArgument;
    }
    // SAFETY: forwarded from the caller.
    unsafe {
        match &mut participant.kind {
            ParticipantKind::Estimated(lock) => {
                insert_in(lock, hash, key, key_len, value, value_len)
            }
            ParticipantKind::Exact(lock) => insert_in(lock, hash, key, key_len, value, value_len),
        }
    }
}

/// `ptr..ptr + len` as a slice; a null or dangling pointer is fine for
/// `len == 0`.
///
/// # Safety
/// For `len != 0`, `ptr` must be valid for `len` bytes.
#[inline(always)]
unsafe fn slice_or_empty<'a>(ptr: *const u8, len: usize) -> &'a [u8] {
    if len == 0 {
        &[]
    } else {
        // SAFETY: guaranteed by the caller; len <= u32::MAX here.
        unsafe { core::slice::from_raw_parts(ptr, len) }
    }
}

#[inline(always)]
unsafe fn lookup_in<P: Params>(
    lock: &mut ParticipantLock<'static, P>,
    hash: u64,
    key: *const u8,
    key_len: usize,
    out_words: *mut u64,
    out_capacity: usize,
    value_len: *mut usize,
) -> Status {
    let hp = lock.cache().params().hot();
    if key_len > hp.max_key_size as usize {
        return Status::KeyTooLarge;
    }
    if value_len.is_null() || out_capacity > isize::MAX as usize {
        return Status::InvalidArgument;
    }
    let out_words_len = out_capacity.div_ceil(8);
    let out_words = if out_words_len == 0 {
        NonNull::dangling().as_ptr()
    } else if out_words.is_null() || !(out_words as usize).is_multiple_of(8) {
        return Status::InvalidArgument;
    } else {
        out_words
    };
    // SAFETY: key_len is bounded and key valid (contract).
    let key = unsafe { slice_or_empty(key, key_len) };
    // SAFETY: out_words holds out_words_len words (contract).
    match unsafe { lock.lookup_raw(hash, key, out_words, out_words_len, out_capacity) } {
        Ok(Some(len)) => {
            // SAFETY: valid for a write (contract).
            unsafe { value_len.write(len) };
            Status::Ok
        }
        Ok(None) => Status::Miss,
        Err(e) => e.into(),
    }
}

#[inline(always)]
unsafe fn insert_in<P: Params>(
    lock: &mut ParticipantLock<'static, P>,
    hash: u64,
    key: *const u8,
    key_len: usize,
    value: *const u8,
    value_len: usize,
) -> Status {
    let hp = lock.cache().params().hot();
    // The size checks precede any slice creation, key first: a call that
    // violates both reports KeyTooLarge.
    if key_len > hp.max_key_size as usize {
        return Status::KeyTooLarge;
    }
    if value_len > hp.max_value_size as usize {
        return Status::ValueTooLarge;
    }
    // SAFETY: lengths bounded and pointers valid (contract).
    let (key, value) = unsafe {
        (
            slice_or_empty(key, key_len),
            slice_or_empty(value, value_len),
        )
    };
    match lock.insert(hash, key, value) {
        Ok(()) => Status::Ok,
        Err(e) => e.into(),
    }
}

/// Bytes needed for a cache with `*config`: the minimum `len` of
/// `ddog_sgc_cache_init_in` (`ddog_sgc_cache_new` maps exactly this much).
/// 0 if `config` is null or invalid.
///
/// # Safety
/// `config` must be null or valid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_cache_mapping_size(config: *const Config) -> usize {
    // SAFETY: forwarded from the caller.
    unsafe { resolve_config(config) }.map_or(0, |d| d.mapping_size)
}

/// Initialises a cache in caller-provided memory and stores a
/// process-local handle in `*out`; `ddog_sgc_cache_new` minus the mapping.
///
/// `mem` must be aligned to 128 bytes on aarch64 and 64 bytes elsewhere (the
/// cache-line size the shared layout is built on; any page-aligned address
/// qualifies) and `len` at least `ddog_sgc_cache_mapping_size(config)`. To
/// share the cache between processes, the memory must be a shared mapping
/// (e.g. `MAP_SHARED`, or a file or `memfd` mapped `MAP_SHARED` by every
/// process) set up before forking or mapped by each process; the caller
/// chooses its pages (huge pages included). `ddog_sgc_cache_free` frees the
/// handle but does not unmap the memory.
///
/// Errors: `INVALID_ARGUMENT` (null arguments, invalid configuration),
/// `MISALIGNED` (`mem` not aligned as above), `INSUFFICIENT_CAPACITY` (`len`
/// too small), `CONCURRENT_OPERATION` (the memory is not zero-filled, e.g.
/// already initialised), `IO_ERROR` (pthread_atfork failed). `*out` is
/// untouched on error.
///
/// # Safety
/// `mem..mem + len` must be zero-filled, valid for reads and writes until
/// the handle is freed, and accessed by others only through this API;
/// `config` and `out` as for `ddog_sgc_cache_new`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ddog_sgc_cache_init_in(
    mem: *mut c_void,
    len: usize,
    config: *const Config,
    out: *mut *mut FfiCache,
) -> Status {
    if out.is_null() {
        return Status::InvalidArgument;
    }
    let Some(base) = NonNull::new(mem.cast::<u8>()) else {
        return Status::InvalidArgument;
    };
    // SAFETY: forwarded from the caller.
    let Some(derived) = (unsafe { resolve_config(config) }) else {
        return Status::InvalidArgument;
    };
    // Checked here, before anything is allocated or installed, although
    // the cache's initialisation checks both too.
    if !(base.as_ptr() as usize).is_multiple_of(crate::util::CACHE_LINE) {
        return Status::Misaligned;
    }
    if len < derived.mapping_size {
        return Status::InsufficientCapacity;
    }
    // SAFETY: forwarded from the caller.
    match unsafe { init_in(base, len, derived, false) } {
        Ok(handle) => {
            // SAFETY: valid (contract).
            unsafe { out.write(Box::into_raw(handle)) };
            Status::Ok
        }
        Err(e) => e.into(),
    }
}
