version: "3.7"

services:

  "5.5-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:5.5"
    build:
      context: .
      args:
        - PHP_VERSION=5.5
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "5.6-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:5.6"
    build:
      context: .
      args:
        - PHP_VERSION=5.6
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "7.0-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:7.0"
    build:
      context: .
      args:
        - PHP_VERSION=7.0
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "7.1-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:7.1"
    build:
      context: .
      args:
        - PHP_VERSION=7.1
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "7.2-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:7.2"
    build:
      context: .
      args:
        - PHP_VERSION=7.2
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "7.3-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:7.3"
    build:
      context: .
      args:
        - PHP_VERSION=7.3
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "7.4-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:7.4"
    build:
      context: .
      args:
        - PHP_VERSION=7.4
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  "8.0-long":
    image: "registry.ddbuild.io/apm-integrations-testing/handmade/php-cli-long:8.0"
    build:
      context: .
      args:
        - PHP_VERSION=8.0
    depends_on:
      - agent
      - httpbin
    env_file: .env
    volumes:
      - ./:/var/app
    command: ["./local-run.sh"]

  httpbin:
    image: kennethreitz/httpbin

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_ENV=testenv
