version: '3.6'

services:

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile_php_fpm
      args:
        DD_TRACER_VERSION: ${DD_TRACER_VERSION}
    depends_on:
      - agent

  nginx:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - php-fpm

  agent:
    image: datadog/agent:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
    - DD_API_KEY=${DATADOG_API_KEY}
