[workspace]
members = [
  "components-rs/php_sidecar_mockgen",
  "sidecar",
  "appsec/helper-rust",
]
# Don't add vendored libddwaf crates to the this workspace; it would break them
exclude = ["appsec/third_party/libddwaf-rust"]
resolver = "2"

[workspace.package]
rust-version = "1.87.0"
edition = "2021"
version = "0.0.1"
license = "Apache-2.0"
authors = ["Datadog Inc. <info@datadoghq.com>"]

[package]
name = "datadog-php"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
build = "components-rs/build.rs"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
path = "components-rs/lib.rs"
bench = false

[features]
default = ["tracer"]
tracer = ["dep:ddtrace-sidecar"]
helper-rust-coverage = ["ddtrace-sidecar/helper-rust-coverage"]
profiling = [
  "dep:cpu-time", "dep:crossbeam-channel", "dep:dashmap", "dep:dynasmrt",
  "dep:libdd-alloc", "dep:libdd-profiling", "dep:mach2", "dep:rand", "dep:rand_distr",
  "dep:rustc-hash", "dep:thiserror", "io_profiling"
]
debug_stats = ["profiling"]
io_profiling = ["profiling"]
stack_walking_tests = ["profiling"]
test = ["profiling"]
tracing = ["profiling"]
tracing-subscriber = ["tracing"]
trigger_time_sample = ["profiling"]

[dependencies]
libdd-common = { path = "libdatadog/libdd-common", features = ["cgroup_testing"] }
libdd-common-ffi = { path = "libdatadog/libdd-common-ffi", default-features = false }
libdd-telemetry = { path = "libdatadog/libdd-telemetry" }
libdd-telemetry-ffi = { path = "libdatadog/libdd-telemetry-ffi", default-features = false }
libdd-live-debugger = { path = "libdatadog/libdd-live-debugger" }
libdd-live-debugger-ffi = { path = "libdatadog/libdd-live-debugger-ffi", default-features = false }
libdd-ipc = { path = "libdatadog/libdd-ipc" }
datadog-ffe = { package = "libdd-ffe", path = "libdatadog/libdd-ffe" }
libdd-remote-config = { path = "libdatadog/libdd-remote-config" }
datadog-sidecar = { path = "libdatadog/datadog-sidecar" }
datadog-sidecar-ffi = { path = "libdatadog/datadog-sidecar-ffi" }
libdd-data-pipeline = { path = "libdatadog/libdd-data-pipeline" }
libdd-tinybytes = { path = "libdatadog/libdd-tinybytes" }
libdd-trace-utils = { path = "libdatadog/libdd-trace-utils" }
libdd-trace-stats = { path = "libdatadog/libdd-trace-stats" }
libdd-trace-protobuf = { path = "libdatadog/libdd-trace-protobuf" }
libdd-crashtracker = { path = "libdatadog/libdd-crashtracker", default-features = false, features = ["collector"] }
libdd-crashtracker-ffi = { path = "libdatadog/libdd-crashtracker-ffi", default-features = false, features = ["collector"] }
libdd-library-config-ffi = { path = "libdatadog/libdd-library-config-ffi", default-features = false }
spawn_worker = { path = "libdatadog/spawn_worker" }
anyhow = "1.0"
const-str = "0.5.6"
itertools = "0.11.0"
serde = "1.0.196"
simd-json = "0.14.1"
serde_with = "3.6.0"
lazy_static = "1.4"
log = { version = "0.4.20", features = ["max_level_trace", "release_max_level_trace"] }
env_logger = "0.11"
zwohash = "0.1.2"
uuid = { version = "1.0", features = ["v4"] }
paste = "1"
tempfile = "3.3"
tracing = { version = "0.1", default-features = false, features = ["std", "attributes"] }
tracing-core = "0.1.32"
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt", "env-filter", "smallvec"] }
serde_json = "1.0.113"
regex = "1.10.5"
regex-automata = "0.4.5"
http = "1.4"
libc = "0.2"
bincode = "1.3.3"
hashbrown = "0.15"
chrono = "0.4"
cpu-time = { version = "1.0", optional = true }
crossbeam-channel = { version = "0.5", default-features = false, features = ["std"], optional = true }
dashmap = { version = "6.2.1", optional = true }
dynasmrt = { version = "5.0.0", optional = true }
libdd-alloc = { path = "libdatadog/libdd-alloc", optional = true }
libdd-profiling = { path = "libdatadog/libdd-profiling", optional = true }
rand = { version = "0.9.4", optional = true }
rand_distr = { version = "0.5.1", optional = true }
rustc-hash = { version = "2.1.3", optional = true }
thiserror = { version = "2", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
libdd-library-config = { path = "libdatadog/libdd-library-config", default-features = false, features = ["otel-thread-ctx", "process-context-reader"] }

# ddtrace-sidecar only adds the AppSec backend registration around libdatadog's daemon entrypoint,
# which is a Unix-only concern. On Windows `run_sidecar` uses `datadog_sidecar` directly instead.
[target.'cfg(unix)'.dependencies]
ddtrace-sidecar = { path = "sidecar", optional = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
mach2 = { version = "0.6.0", optional = true }

[build-dependencies]
cbindgen = "0.27"
bindgen = "0.72.1"
cc = "1.0"

[dev-dependencies]
criterion = "0.5.1"
static_assertions = "1"

[target.'cfg(target_arch = "x86_64")'.dev-dependencies]
criterion-perf-events = "0.4.0"
perfcnt = "0.8.0"

[[bench]]
name = "stack_walking"
path = "profiling/benches/stack_walking.rs"
harness = false
required-features = ["profiling", "test"]

[profile.dev]
debug = 2

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = false
lto = "fat"

[profile.tracer-release]
debug = 1
lto = true
codegen-units = 1
panic = "abort"
inherits = "release"

[profile.profiler-release]
panic = "abort"
inherits = "release"

[workspace.dependencies]
allocator-api2 = { version = "0.2.21", default-features = false }
anyhow = { version = "1.0", default-features = false }
arbitrary = { version = "1.3", default-features = false }
arc-swap = { version = "1.7.1", default-features = false }
arrayref = { version = "0.3.7", default-features = false }
assert_no_alloc = { version = "1.1.2", default-features = false }
async-trait = { version = "0.1", default-features = false }
base64 = { version = "0.22", default-features = false }
bincode = { version = "1.3.3", default-features = false }
bitmaps = { version = "3.2.0", default-features = false }
blazesym = { version = "=0.2.3", default-features = false }
bolero = { version = "0.13.4", default-features = false }
byteorder = { version = "1.5", default-features = false }
bytes = { version = "1.11", default-features = false }
cadence = { version = "1.3.0", default-features = false }
cargo-platform = { version = "=0.1.7", default-features = false }
cargo_metadata = { version = "0.18.1", default-features = false }
cc = { version = "1.1.31", default-features = false }
chrono = { version = "0.4.38", default-features = false }
clap = { version = "4.3.21", default-features = false }
console-subscriber = { version = "0.5", default-features = false }
const_format = { version = "0.2.34", default-features = false }
constcat = { version = "0.4.1", default-features = false }
criterion = { version = "0.5.1", default-features = true }
crossbeam-channel = { version = "0.5.15", default-features = false }
crossbeam-queue = { version = "0.3.11", default-features = false }
crossbeam-utils = { version = "0.8.21", default-features = false }
cxx = { version = "1.0", default-features = false }
cxx-build = { version = "1.0", default-features = false }
derive_more = { version = "2.0.0", default-features = false }
duplicate = { version = "2.0.1", default-features = false }
either = { version = "1.13.0", default-features = false }
elf = { version = "0.7", default-features = false }
errno = { version = "0.3", default-features = false }
fastrand = { version = "2", default-features = false }
faststr = { version = "0.2.23", default-features = false }
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
fluent-uri = { version = "0.4.1", default-features = false }
function_name = { version = "0.3.0", default-features = false }
futures = { version = "0.3", default-features = false }
futures-channel = { version = "0.3", default-features = false }
futures-core = { version = "0.3.0", default-features = false }
futures-util = { version = "0.3.0", default-features = false }
getrandom = { version = "0.2", default-features = false }
glibc_version = { version = "0.1.2", default-features = false }
goblin = { version = "0.9.3", default-features = false }
h2 = { version = "0.4", default-features = false }
hashbrown = { version = "0.17", default-features = false }
heck = { version = "0.5", default-features = false }
hex = { version = "0.4", default-features = false }
http = { version = "1.1", default-features = false }
http-body = { version = "1", default-features = false }
http-body-util = { version = "0.1", default-features = false }
httpmock = { version = "0.8.0-alpha.1", default-features = false, features = ["cookies"] }
httparse = { version = "1.9", default-features = false }
hyper = { version = "1.6", default-features = false }
hyper-rustls = { version = "0.27.7", default-features = false }
hyper-util = { version = "0.1.10", default-features = false }
indexmap = { version = "2.11", default-features = false }
io-lifetimes = { version = "1.0", default-features = false }
itoa = { version = "1.0", default-features = false }
libc = { version = "0.2", default-features = true }
libdd-libunwind-sys = { version = "1.0.3", default-features = false }
log = { version = "0.4.21", default-features = false }
lru = { version = "0.16.3", default-features = false }
manual_future = { version = "0.1.1", default-features = false }
maplit = { version = "1.0", default-features = false }
md5 = { version = "0.7.0", default-features = false }
memfd = { version = "0.6", default-features = false }
memory-stats = { version = "1.2.0", default-features = false }
microseh = { version = "0.1.1", default-features = false }
mime = { version = "0.3.16", default-features = false }
multer = { version = "3.1", default-features = false }
nix = { version = "0.29", default-features = false }
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
object = { version = "0.36", default-features = false }
once_cell = { version = "1.18", default-features = false }
os_info = { version = "3.14.0", default-features = false }
page_size = { version = "0.6.0", default-features = false }
parking_lot = { version = "0.12", default-features = false }
paste = { version = "1", default-features = false }
percent-encoding = { version = "2.1", default-features = false }
pin-project = { version = "1", default-features = false }
portable-atomic = { version = "1.6.0", default-features = false }
prctl = { version = "1.0.0", default-features = false }
pretty_assertions = { version = "1.3", default-features = false }
priority-queue = { version = "2.1.1", default-features = false }
proc-macro2 = { version = "1", default-features = false }
proptest = { version = "1", default-features = false }
prost = { version = "0.14.1", default-features = false }
prost-build = { version = "0.14.1", default-features = false }
protoc-bin-vendored = { version = "3.0.0", default-features = false }
pyo3 = { version = "0.28", default-features = false }
quote = { version = "1", default-features = false }
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
regex = { version = "1.5", default-features = false }
regex-lite = { version = "0.1", default-features = false }
reqwest = { version = "0.13", default-features = false }
ring = { version = "0.17", default-features = false }
rlimit = { version = "0.9", default-features = false }
rmp = { version = "0.8.14", default-features = false }
rmp-serde = { version = "1.3.0", default-features = false }
rmpv = { version = "1.3.0", default-features = false }
rustc-hash = { version = "2.1.1", default-features = false }
rustls = { version = "0.23", default-features = false }
rustls-native-certs = { version = ">=0.8.1, <0.8.3", default-features = false }
rustls-platform-verifier = { version = "0.6", default-features = false }
rustls-webpki = { version = ">=0.103.13", default-features = false }
schemars = { version = "0.8.21", default-features = false }
semver = { version = "1.0", default-features = false }
sendfd = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false }
serde-bool = { version = "0.1.3", default-features = false }
serde-transcode = { version = "1.1", default-features = false }
serde_bytes = { version = "0.11.9", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde_with = { version = "3.11.0", default-features = false }
serde_yaml = { version = "0.9.34", default-features = false }
serial_test = { version = "3.2", default-features = false }
sha2 = { version = "0.10", default-features = false }
simd-json = { version = "=0.14", default-features = false }
smallvec = { version = "1.13.2", default-features = false }
static_assertions = { version = "1.1.0", default-features = false }
strum = { version = "0.26.2", default-features = false }
strum_macros = { version = "0.26", default-features = false }
symbolic-common = { version = "12.8.0", default-features = false }
symbolic-demangle = { version = "12.8.0", default-features = false }
syn = { version = "^2", default-features = false }
sys-info = { version = "0.9.0", default-features = false }
target-triple = { version = "0.1.4", default-features = false }
tempfile = { version = "3.13", default-features = false, features = ["getrandom"] }
test-case = { version = "2.2", default-features = false }
thin-vec = { version = "0.2", default-features = false }
thiserror = { version = "2.0.3", default-features = false }
thread_local = { version = "1.1", default-features = false }
time = { version = "0.3", default-features = false }
tokio = { version = "1.36", default-features = false }
tokio-rustls = { version = "0.26", default-features = false }
tokio-util = { version = "0.7.11", default-features = false }
tonic = { version = "0.14", default-features = false }
tower-service = { version = "0.3", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-appender = { version = "0.2.3", default-features = false }
tracing-log = { version = "0.2.0", default-features = false }
tracing-subscriber = { version = "0.3.22", default-features = false }
tuf = { package = "libdd-tuf", version = "0.3.1", default-features = false }
url = { version = "2.5.0", default-features = false }
urlencoding = { version = "2.1.3", default-features = false }
uuid = { version = "1.7.0", default-features = false }
wasm-bindgen-futures = { version = "0.4", default-features = false }
web-time = { version = "1", default-features = false }
winver = { version = "1.0.0", default-features = false }
zrip = { version = "=0.6.0", default-features = false }
zstd = { version = "0.13", default-features = false }
zwohash = { version = "0.1.2", default-features = false }

[workspace.lints]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(php_shared_build)', 'cfg(stack_walking_tests)'] }
