# Validate using: cat codecov.yml | curl --data-binary @- https://codecov.io/validate
codecov:
  require_ci_to_pass: false

coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project: off
    patch: off

comment: # See https://docs.codecov.com/docs/pull-request-comments
  behavior: default
  require_changes: false
  require_head: false
  require_base: false
  layout: "reach,diff,flags,files"
