# Validate using: cat codecov.yml | curl --data-binary @- https://codecov.io/validate
codecov:
  require_ci_to_pass: false # See coverage on CI test failures

coverage:
  range: 90..100
  round: down
  precision: 2
  status: # Blocking coverage targets
    project: # Each PR must increase coverage
      default:
        target: auto
    patch: # New code must be at least 90% tested
      default:
        target: 90%


comment: # See https://docs.codecov.com/docs/pull-request-comments
  behavior: default
  layout: "header,reach,diff,flags,files,footer"
  require_changes: true
  require_base: false
  require_head: false
