"""Public LLVM target runtime provider."""

LlvmRuntimeInfo = provider(
    doc = "Relocatable libc++, libc++abi, libunwind, and compiler-rt builtins for one target.",
    fields = {
        "header_root": "Independent libc++ header tree.",
        "compile_inputs": "Headers only; no runtime libraries or validation binaries.",
        "link_inputs": "Normal target libraries and startup objects.",
        "builtin_inputs": "Compiler builtins and startup objects.",
        "sanitizer_inputs": "Dedicated sanitizer artifacts and resource directory.",
        "validation_inputs": "Explicit runtime smoke executables.",
        "root": "Relocatable installed runtime tree artifact.",
        "files": "depset containing the tree and explicit link artifacts.",
        "headers": "depset containing the libc++ headers tree.",
        "libraries": "ordered tuple: libc++, libc++abi, libunwind, builtins.",
        "libcxx_static": "libc++.a File.",
        "libcxx_shared": "libc++.so.1 File.",
        "libcxxabi_static": "libc++abi.a File.",
        "libcxxabi_shared": "libc++abi.so.1 File.",
        "libunwind_static": "libunwind.a File.",
        "libunwind_shared": "libunwind.so.1 File.",
        "builtins_static": "compiler-rt builtins archive File.",
        "crtbegin": "compiler-rt crtbegin object File.",
        "crtend": "compiler-rt crtend object File.",
        "startup_crt1": "Target crt1.o with package-build DWARF removed.",
        "startup_pie_crt1": "Target PIE startup object with package-build DWARF removed.",
        "startup_crti": "Target crti.o with package-build DWARF removed.",
        "startup_crtn": "Target crtn.o with package-build DWARF removed.",
        "resource_dir": "Tree whose lib/linux directory contains compiler-rt artifacts.",
        "builtins_basename": "Target-specific compiler-rt builtins archive basename.",
        "asan_supported": "Whether this target runtime includes AddressSanitizer.",
        "asan_shared": "AddressSanitizer shared runtime File, or None.",
        "asan_static": "AddressSanitizer C static runtime File, or None.",
        "asan_cxx_static": "AddressSanitizer C++ static runtime File, or None.",
        "asan_preinit_static": "AddressSanitizer executable preinit archive File, or None.",
        "asan_shared_basename": "Canonical ASan DT_SONAME basename, or None.",
        "cxx20_smoke": "Static target C++20 validation executable File.",
        "target_triple": "LLVM target triple.",
        "libc": "glibc or musl.",
        "libc_version": "Target libc compatibility floor.",
    },
)
