pull:
	@docker-compose pull

clean_results:
	@rm -rf ./.results/*
	@echo "Results folder cleaned"

test.scenario.%:
	@docker-compose run $(*)

# Dynamically generated targets will be added after this line
