user www-data;
worker_processes 2;
pid /run/nginx.pid;
error_log /dev/stderr notice;

events {
    worker_connections 16384;
}

http {
    access_log off;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;
        root /app/public;

        location / {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /app/public/index.php;
            fastcgi_param SCRIPT_NAME /index.php;
            fastcgi_pass 127.0.0.1:9000;
        }
    }
}
