// Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/). Copyright 2026-Present Datadog, Inc.

// Mutex-free, process-shared, two-generation byte cache (see shm_gen_cache/README.md).
// Generated by cbindgen from shm_gen_cache/src/ffi.rs; do not edit.

#ifndef DDOG_SHM_GEN_CACHE_H
#define DDOG_SHM_GEN_CACHE_H

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Status codes. The numeric values are stable API (2-15 are errors).
 */
typedef enum ddog_sgc_Status {
  /**
   * Success (lookup: hit).
   */
  DDOG_SGC_STATUS_OK = 0,
  /**
   * Lookup: the key is not cached.
   */
  DDOG_SGC_STATUS_MISS = 1,
  /**
   * Lookup: the value does not fit the output capacity.
   */
  DDOG_SGC_STATUS_INSUFFICIENT_CAPACITY = 2,
  /**
   * The key is longer than the configured maximum.
   */
  DDOG_SGC_STATUS_KEY_TOO_LARGE = 3,
  /**
   * The value is longer than the configured maximum.
   */
  DDOG_SGC_STATUS_VALUE_TOO_LARGE = 4,
  /**
   * Not returned by this API.
   */
  DDOG_SGC_STATUS_INVALID_MAPPING = 5,
  /**
   * Every participant slot is taken by a live registration.
   */
  DDOG_SGC_STATUS_PARTICIPANT_REGISTRY_FULL = 6,
  /**
   * Not returned by this API.
   */
  DDOG_SGC_STATUS_FULL_RETRY = 7,
  /**
   * Null/misaligned arguments, invalid configuration, overlapping
   * buffers, or a participant inherited across fork().
   */
  DDOG_SGC_STATUS_INVALID_ARGUMENT = 8,
  /**
   * A system call failed (mmap/VirtualAlloc, or the liveness backend's
   * membarrier or thread wait).
   */
  DDOG_SGC_STATUS_IO_ERROR = 9,
  /**
   * Unsupported platform or kernel feature.
   */
  DDOG_SGC_STATUS_UNSUPPORTED = 10,
  /**
   * Internal race; not returned by lookup/insert.
   */
  DDOG_SGC_STATUS_CONCURRENT_OPERATION = 11,
  /**
   * A participant slot was corrupted.
   */
  DDOG_SGC_STATUS_CORRUPT = 12,
  /**
   * The mapping is not cache-line aligned.
   */
  DDOG_SGC_STATUS_MISALIGNED = 13,
  /**
   * The rotation owner stayed busy (and alive) through the wait budget.
   */
  DDOG_SGC_STATUS_ROTATION_OWNER_TIMEOUT = 14,
  /**
   * A live participant pinned to the arena being reused did not unpin in
   * time.
   */
  DDOG_SGC_STATUS_ARENA_REUSE_TIMEOUT = 15,
} ddog_sgc_Status;

/**
 * A process-local cache handle (C `ddog_sgc_Cache`, opaque).
 *
 * Usage model: `ddog_sgc_cache_new` once, in the parent before forking;
 * each thread of each process registers a participant
 * (`ddog_sgc_participant_register`), uses it for lookups and inserts, and
 * unregisters it; `ddog_sgc_cache_free` once no participant of the process
 * is registered.
 *
 * Process safety: any number of processes sharing the mapping (fork()ed
 * after `ddog_sgc_cache_new`) may operate concurrently. On Linux they must
 * share PID and time namespaces, with `/proc` mounted for them (the
 * liveness backend identifies participants by kernel TID and start time).
 * On Windows, which has no fork(), only the threads of one process share a
 * cache (the liveness backend identifies participants by thread ID and
 * creation time). A mapping must never be reused across boots. Other
 * platforms use a no-op liveness backend (dead participants are never
 * reaped): development only.
 *
 * A `ddog_sgc_Cache` may be used from any thread for registration.
 *
 * No call blocks indefinitely: waits are bounded (5 ms of wall-clock time
 * each) and end in the `*_TIMEOUT` statuses. A process that dies
 * registered (even mid-insert) is recovered by slot reaping; until its slot
 * is reaped, its pin can delay arena reuse.
 */
typedef struct ddog_sgc_Cache ddog_sgc_Cache;

/**
 * A process-local participant handle (C `ddog_sgc_Participant`, opaque).
 *
 * Thread safety: a participant belongs to the thread that registered it:
 * lookup, insert and unregister only from that thread, never concurrently,
 * and never from a signal handler.
 *
 * Fork: in a fork()ed child an inherited participant is unusable (lookup
 * and insert return `DDOG_SGC_STATUS_INVALID_ARGUMENT`; unregister only
 * frees the handle); the child must register its own.
 */
typedef struct ddog_sgc_Participant ddog_sgc_Participant;

/**
 * Cache configuration; also the C API's `ddog_sgc_Config`.
 *
 * Zero in `record_area_size`, `max_occupancy` or `reservation_chunk_size`
 * selects the default for that field (a zero value would be invalid for the
 * first two; for the third, zero is also how the default is stored).
 */
typedef struct ddog_sgc_Config {
  /**
   * Participant slots: at most this many registrations at once.
   */
  uint32_t participant_capacity;
  /**
   * Index entries per arena: a power of two and a multiple of 8.
   */
  uint32_t bucket_count;
  /**
   * Longest key, in bytes.
   */
  uint32_t max_key_size;
  /**
   * Longest value, in bytes.
   */
  uint32_t max_value_size;
  /**
   * Record bytes per arena: a positive multiple of 8 below 2^31. Zero
   * selects `bucket_count * (16 + align8(max_key_size) +
   * align8(max_value_size))`.
   */
  uint32_t record_area_size;
  /**
   * Positive rotation target (entries per arena); already-reserved
   * records may exceed it. Zero selects `(uint32_t)(bucket_count * 0.7)`.
   */
  uint32_t max_occupancy;
  /**
   * Bytes claimed at once from an arena's record area. Subsequent records
   * use the participant's remaining chunk without a shared reservation
   * RMW. Must be a multiple of 8 and no larger than the record area. Zero
   * selects exactly five times the largest record (including headers and
   * separate key/value padding); it does not disable batching. A record
   * at least as large as the chunk, or one near capacity when a whole
   * chunk no longer fits, claims just its own size. A tail is abandoned
   * when the next record does not fit in it, on rotation, and when the
   * participant's registration ends.
   */
  uint32_t reservation_chunk_size;
  /**
   * Forces an exact shared occupancy counter even where the estimator
   * would be selected.
   */
  bool always_exact_occupancy;
} ddog_sgc_Config;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allocates and initialises a cache.
 *
 * Validates `*config` (`DDOG_SGC_STATUS_INVALID_ARGUMENT` on any violation
 * of the configuration rules documented on `ddog_sgc_Config`), maps the
 * cache's size `MAP_SHARED | MAP_ANONYMOUS` (zero-filled, page-aligned,
 * inherited by fork()ed children together with the handle), initialises it
 * in place and stores a process-local handle in `*out`. On Windows, which
 * has no fork(), the memory is `VirtualAlloc`ed and private to the
 * process.
 *
 * On Linux the mapping is advised `MADV_HUGEPAGE` before initialisation.
 * It is backed by 2 MiB pages only if
 * `/sys/kernel/mm/transparent_hugepage/shmem_enabled` allows it (`advise`,
 * `always` or `within_size`; not `never`), and pages the kernel cannot
 * allocate huge stay 4 KiB (`ShmemPmdMapped` in `/proc/PID/smaps` shows
 * how much is huge).
 *
 * Errors: `INVALID_ARGUMENT` (null arguments, invalid configuration),
 * `IO_ERROR` (mmap, VirtualAlloc or pthread_atfork failed), `UNSUPPORTED`
 * (neither Unix nor Windows). `*out` is untouched on error.
 *
 * # Safety
 * `config` must be null or point to a valid config; `out` must be null or
 * valid for a pointer write.
 */
enum ddog_sgc_Status ddog_sgc_cache_new(const struct ddog_sgc_Config *config,
                                        struct ddog_sgc_Cache **out);

/**
 * Frees the handle and, for a cache from `ddog_sgc_cache_new`, unmaps this
 * process's view of it (other processes keep their mappings; memory given
 * to `ddog_sgc_cache_init_in` stays the caller's). NULL is a no-op.
 *
 * # Safety
 * `cache` must be null or a handle from `ddog_sgc_cache_new` or
 * `ddog_sgc_cache_init_in` not yet freed, and no participant of this
 * process may still be registered with it (participant handles borrow the
 * mapping).
 */
void ddog_sgc_cache_free(struct ddog_sgc_Cache *cache);

/**
 * Claims a participant slot for the calling thread, reaping a dead
 * participant's slot when the registry is full, and stores a process-local
 * handle in `*out`.
 *
 * Errors: `PARTICIPANT_REGISTRY_FULL`; `IO_ERROR` / `UNSUPPORTED` (liveness
 * backend, during slot reaping); `CORRUPT`; `INVALID_ARGUMENT` (null
 * arguments). `*out` is untouched on error.
 *
 * # Safety
 * `cache` must be null or a live handle; `out` null or valid for a pointer
 * write.
 */
enum ddog_sgc_Status ddog_sgc_participant_register(const struct ddog_sgc_Cache *cache,
                                                   struct ddog_sgc_Participant **out);

/**
 * Releases the participant's slot and frees the handle. Must
 * be called on the registering thread; aborts the process if the slot's
 * state was corrupted. In a fork()ed child of the registering process it
 * only frees the handle (the slot belongs to the parent's thread). NULL is
 * a no-op.
 *
 * # Safety
 * `participant` must be null or a live handle from
 * `ddog_sgc_participant_register`, whose cache is still allocated.
 */
void ddog_sgc_participant_unregister(struct ddog_sgc_Participant *participant);

/**
 * Looks `key` up.
 *
 * * Hit: `OK`; `*value_len` is the value's length and the value is in the
 *   first `*value_len` bytes of `out_words`.
 * * Miss: `MISS`.
 * * A hit larger than `out_capacity`: `INSUFFICIENT_CAPACITY`.
 * * `key_len` above the configured maximum: `KEY_TOO_LARGE` (checked
 *   first, before any pointer is used).
 * * Called in a fork()ed child of the registering process, null
 *   `value_len`, null or misaligned `out_words` with a non-zero capacity,
 *   or `key` overlapping the output storage: `INVALID_ARGUMENT`.
 *
 * `out_words` must be 8-byte aligned with room for `ceil(out_capacity / 8)`
 * words: whole words are copied. `value_len` must not point into that
 * storage: the length is written after the value. `key` may be NULL iff
 * `key_len == 0`.
 * `out_words` contents are unspecified unless `OK`; `*value_len` is written
 * only on `OK`. A hit in the previous generation is promoted (inserted into
 * the current one); a promotion error is returned instead of `OK`
 * (`ROTATION_OWNER_TIMEOUT`, `ARENA_REUSE_TIMEOUT`, `IO_ERROR`, ...).
 *
 * # Safety
 * `participant` must be a live handle used on its registering thread;
 * `key` valid for `key_len` bytes; `out_words` valid for
 * `ceil(out_capacity / 8)` words; `value_len` valid for a write and
 * outside those words.
 */
enum ddog_sgc_Status ddog_sgc_lookup(struct ddog_sgc_Participant *participant,
                                     uint64_t hash,
                                     const uint8_t *key,
                                     size_t key_len,
                                     uint64_t *out_words,
                                     size_t out_capacity,
                                     size_t *value_len);

/**
 * Inserts or replaces `key` -> `value`.
 *
 * Returns `OK`, or `KEY_TOO_LARGE` / `VALUE_TOO_LARGE` (checked before any
 * pointer is used), `ROTATION_OWNER_TIMEOUT`, `ARENA_REUSE_TIMEOUT`,
 * `IO_ERROR`, `UNSUPPORTED`, `CORRUPT`, or `INVALID_ARGUMENT` in a fork()ed
 * child of the registering process. NULL pointers are allowed only with
 * zero lengths. Use the same hash for a key in every process.
 *
 * # Safety
 * `participant` must be a live handle used on its registering thread;
 * `key` and `value` valid for their lengths.
 */
enum ddog_sgc_Status ddog_sgc_insert(struct ddog_sgc_Participant *participant,
                                     uint64_t hash,
                                     const uint8_t *key,
                                     size_t key_len,
                                     const uint8_t *value,
                                     size_t value_len);

/**
 * Bytes needed for a cache with `*config`: the minimum `len` of
 * `ddog_sgc_cache_init_in` (`ddog_sgc_cache_new` maps exactly this much).
 * 0 if `config` is null or invalid.
 *
 * # Safety
 * `config` must be null or valid.
 */
size_t ddog_sgc_cache_mapping_size(const struct ddog_sgc_Config *config);

/**
 * Initialises a cache in caller-provided memory and stores a
 * process-local handle in `*out`; `ddog_sgc_cache_new` minus the mapping.
 *
 * `mem` must be aligned to 128 bytes on aarch64 and 64 bytes elsewhere (the
 * cache-line size the shared layout is built on; any page-aligned address
 * qualifies) and `len` at least `ddog_sgc_cache_mapping_size(config)`. To
 * share the cache between processes, the memory must be a shared mapping
 * (e.g. `MAP_SHARED`, or a file or `memfd` mapped `MAP_SHARED` by every
 * process) set up before forking or mapped by each process; the caller
 * chooses its pages (huge pages included). `ddog_sgc_cache_free` frees the
 * handle but does not unmap the memory.
 *
 * Errors: `INVALID_ARGUMENT` (null arguments, invalid configuration),
 * `MISALIGNED` (`mem` not aligned as above), `INSUFFICIENT_CAPACITY` (`len`
 * too small), `CONCURRENT_OPERATION` (the memory is not zero-filled, e.g.
 * already initialised), `IO_ERROR` (pthread_atfork failed). `*out` is
 * untouched on error.
 *
 * # Safety
 * `mem..mem + len` must be zero-filled, valid for reads and writes until
 * the handle is freed, and accessed by others only through this API;
 * `config` and `out` as for `ddog_sgc_cache_new`.
 */
enum ddog_sgc_Status ddog_sgc_cache_init_in(void *mem,
                                            size_t len,
                                            const struct ddog_sgc_Config *config,
                                            struct ddog_sgc_Cache **out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DDOG_SHM_GEN_CACHE_H */
