<?php

echo "This is footer\n";

$var = <<<TEXT
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus id ligula varius tellus hendrerit posuere. Nulla iaculis ipsum mauris, in luctus tellus ultricies ut. Aliquam tempor felis sit amet ipsum ultricies porta. In volutpat ligula gravida eleifend vulputate. Praesent ornare tincidunt sodales. Nam purus erat, tincidunt non euismod vitae, tempus et ligula. Duis fermentum leo sapien, et fermentum libero ornare vel. Pellentesque nulla ex, tincidunt nec neque nec, tincidunt semper sapien. Vivamus condimentum velit non nisl luctus volutpat. Nam iaculis blandit felis eu pharetra.
Phasellus velit orci, mattis non egestas ac, condimentum a orci. Mauris vehicula mi vel massa feugiat congue nec at orci. Ut porttitor ac tellus sit amet tempus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus arcu quam, efficitur ac orci ut, efficitur rhoncus orci. Nam aliquet ipsum eget lectus congue, imperdiet dignissim lacus lobortis. Fusce at scelerisque ipsum, et congue tortor. Etiam vel vulputate ipsum, sit amet cursus eros.

Maecenas quis dignissim metus, vitae blandit quam. Phasellus ac semper nisl, tincidunt commodo mauris. Quisque ut nisi eros. Vestibulum vel diam placerat, aliquam orci eget, sollicitudin mauris. Nam varius rhoncus nunc. Phasellus id erat a tellus consectetur lacinia at ac metus. Integer eget molestie eros, et lobortis tellus. Nulla facilisi.

Quisque posuere turpis lacus, fermentum rutrum justo rutrum bibendum. Vivamus porta ullamcorper libero, quis rutrum felis pellentesque et. Nullam eu ante risus. Suspendisse sagittis, erat id accumsan convallis, sapien augue feugiat nibh, aliquam dignissim quam lacus vel tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam sollicitudin et lorem sed luctus. Vivamus sit amet imperdiet libero, nec fermentum felis. Nam non ipsum eu magna dictum sagittis quis at arcu. Praesent fringilla aliquam molestie. Cras ex dolor, ultricies sit amet lorem ac, maximus vestibulum urna. Cras sed consequat quam, et consequat nisl.

Aliquam justo elit, vestibulum hendrerit dapibus vitae, porta vel turpis. Suspendisse ante quam, tempor in malesuada laoreet, interdum id urna. Nullam tempor massa ut felis lobortis feugiat. Suspendisse sit amet placerat quam. Donec nec consequat nibh. In congue tellus a justo egestas blandit. Proin non metus ex. Nulla quis ipsum a ipsum fermentum dictum cursus vel lorem. Integer condimentum consectetur neque porttitor convallis. Integer sed condimentum erat, non condimentum nunc. Curabitur et fringilla risus. Nulla consectetur turpis nec eros mollis, ac laoreet lacus fermentum.

In iaculis a lorem in ultricies. Proin dignissim lectus vel placerat finibus. Mauris molestie eget nulla eget fringilla. Donec tristique magna ut mattis congue. Nam ullamcorper tempus nisi, sed convallis orci sollicitudin et. Donec elit dolor, commodo id finibus id, tempor vel dui. Pellentesque ligula risus, vulputate eget consectetur vel, laoreet et lacus.

Integer feugiat dui fringilla malesuada molestie. Ut dapibus est eget nibh sollicitudin pellentesque. Sed nulla leo, laoreet sed tristique et, tincidunt a neque. Nullam ultrices sem sit amet nulla eleifend, sed viverra metus commodo. Fusce auctor lectus in leo gravida, eget ornare urna pulvinar. Ut eget commodo nisl, a vulputate metus. Vestibulum nec dolor ut erat scelerisque sollicitudin vitae a nulla. Ut scelerisque, neque et elementum finibus, nunc urna auctor nulla, in tincidunt tellus nisi id mauris. Mauris pretium enim eget nulla pellentesque gravida. Donec id magna ut purus auctor convallis sit amet ut orci. Sed risus risus, pellentesque in pretium vel, accumsan eu nibh. Etiam molestie tincidunt dui ut gravida. Etiam euismod, velit in condimentum bibendum, felis velit aliquam tellus, sed iaculis tortor nisi a ex. Curabitur cursus interdum rhoncus.

Maecenas quis sollicitudin mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras non felis in magna ornare vulputate. Mauris viverra tortor laoreet, dignissim dolor ultrices, bibendum enim. Proin imperdiet dui a est egestas sollicitudin. Sed euismod, leo at consectetur luctus, nibh ante cursus orci, vitae consequat dui mauris at purus. In congue mi at aliquam scelerisque. Etiam imperdiet in leo molestie egestas. Fusce blandit elit ac tortor ultrices, vitae cursus ligula pharetra. Praesent finibus augue ut metus viverra scelerisque. Morbi scelerisque neque quis risus facilisis, sit amet tempus elit placerat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis enim ullamcorper, aliquam metus fringilla, volutpat neque. Cras dapibus lacus ut turpis mattis lacinia. Quisque nec urna et ipsum tempor rutrum. Integer semper neque auctor commodo pharetra.

Sed facilisis, mi ac dictum dictum, elit eros tincidunt diam, sit amet auctor quam augue nec sem. Curabitur dictum sed orci quis fermentum. Mauris tincidunt lectus purus, in congue lacus lobortis ut. Sed nec lectus tincidunt, venenatis est eget, lobortis urna. Suspendisse potenti. Integer tristique sollicitudin dictum. Fusce in enim tellus. Aliquam nec enim sed sapien commodo aliquet. Curabitur porta arcu sapien, et congue nisi semper quis. Nulla bibendum lorem nec magna scelerisque, sed dapibus massa fringilla. Proin ut nibh risus. Aenean congue viverra ullamcorper. Donec ipsum nisi, egestas et orci et, sollicitudin congue massa. Nunc massa libero, faucibus nec metus vel, elementum ullamcorper mauris.

Aliquam gravida diam ac ultricies condimentum. Donec vestibulum pellentesque gravida. Maecenas facilisis est ac erat vehicula viverra. Maecenas sed dolor diam. Nulla tempus, tellus suscipit euismod porttitor, libero quam lacinia metus, eget consequat turpis nunc eu lacus. Integer dignissim arcu ligula, at molestie arcu bibendum at. Praesent arcu risus, dignissim eget lorem ac, tempus dapibus dui. In at orci iaculis, aliquam ipsum eget, suscipit metus. Suspendisse et maximus massa. Ut eleifend turpis lacus, et sagittis turpis vestibulum in. Suspendisse dictum, enim a semper cursus, nisl lacus aliquam sem, eu tincidunt sapien leo non sapien. Nulla a mi at libero tristique condimentum. Quisque blandit dictum turpis et scelerisque. Etiam pretium arcu eu sem varius vehicula. Sed non felis eu neque lacinia luctus. Aenean elementum rutrum rhoncus.

Pellentesque tempor rhoncus mauris et bibendum. Proin vitae consectetur mauris. Curabitur eros purus, aliquam nec consectetur non, interdum nec sem. Nulla facilisi. Ut feugiat a massa a dignissim. Vestibulum id orci nibh. Vestibulum venenatis in elit aliquam sodales. Duis vehicula suscipit lorem, eu lacinia massa feugiat at. Donec tempor tellus in libero egestas, sit amet aliquet diam imperdiet. Suspendisse ultrices, nunc et porttitor ultrices, turpis odio maximus orci, non consectetur leo neque sed purus. Nullam vestibulum, ipsum eget porttitor ullamcorper, turpis nulla volutpat mauris, molestie suscipit elit ipsum quis metus. Aenean aliquam elit quam, at vehicula diam pulvinar vitae. Nulla quis condimentum nibh, non scelerisque ex. Quisque volutpat tincidunt lacus, quis rutrum dolor aliquam quis.

Fusce dapibus interdum odio et cursus. Cras condimentum est libero, tincidunt faucibus est consequat eget. Duis semper tempor interdum. Sed eu commodo metus, non consequat libero. Suspendisse feugiat dolor metus, ut posuere augue dignissim nec. Suspendisse tempor, tellus sed tempus consectetur, urna neque porttitor eros, sed tincidunt mauris mi eu neque. Fusce scelerisque justo et ex malesuada, non dapibus orci fermentum. Aenean quis nisi erat. Maecenas cursus commodo magna imperdiet feugiat. Sed tempor tortor malesuada suscipit consequat. Pellentesque in nibh non risus aliquam imperdiet. Pellentesque tellus justo, efficitur eget fringilla sed, cursus et nulla. Nunc consectetur purus urna, nec posuere felis hendrerit vel. Maecenas eleifend mi cursus tortor dictum interdum. Proin elementum leo augue, sed volutpat risus efficitur sit amet.

Nullam eget sapien id eros auctor elementum nec vitae dui. Morbi consequat at lacus nec tincidunt. In feugiat enim enim, in pellentesque risus faucibus sed. Aliquam quis dui bibendum, blandit orci ut, tincidunt nunc. Pellentesque vulputate imperdiet cursus. Ut vitae leo faucibus, egestas metus quis, faucibus massa. Morbi tortor ligula, condimentum sit amet arcu vel, lobortis rhoncus tellus. Fusce facilisis pulvinar augue, et egestas metus malesuada a. Aliquam vel fermentum odio, in fringilla tellus. Morbi porta, libero non bibendum placerat, est purus mattis risus, et sodales ex lacus sed lectus. Donec gravida pellentesque mauris at hendrerit. Vestibulum sit amet odio ut diam eleifend varius. Sed ornare, magna vel rhoncus imperdiet, nunc tortor mollis arcu, et pellentesque odio tortor sit amet tortor. Quisque dapibus, orci sed consectetur condimentum, mauris lacus condimentum eros, in bibendum elit elit in felis.

Ut congue laoreet augue, eu finibus justo euismod non. Vestibulum scelerisque libero at sagittis euismod. Donec placerat nibh sed dapibus fermentum. Sed commodo nec magna a vulputate. Donec non iaculis tellus. Aenean eu libero nisl. Aenean consequat turpis sit amet semper imperdiet. Morbi pharetra mi vitae facilisis hendrerit.

Donec lacinia dolor eget mauris feugiat, quis ornare dui auctor. Donec a mattis augue. Nulla vestibulum viverra orci, id porttitor lacus rhoncus vitae. Curabitur cursus mollis tellus at pulvinar. Donec sit amet orci et mi volutpat mollis ac quis magna. Phasellus lacinia convallis leo. Vivamus iaculis ligula vitae ligula blandit venenatis. Proin pellentesque felis in quam dignissim dictum. Nulla gravida purus massa, ac mollis sem euismod ac. Morbi posuere commodo viverra. Fusce finibus malesuada nisi quis posuere. Donec nec mauris arcu. ";
TEXT;
