<?php

// posix_kill(posix_getpid(), 11);
// exit();

require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
require __DIR__ . '/header.php';
require __DIR__ . '/content.php';
require __DIR__ . '/footer.php';
