version: '3.7'

services:

  base:
    image: datadog/dd-trace-ci:alpine
    build:
      context: .

  php-8.0:
    image: datadog/dd-trace-ci:php-8.0_alpine
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.15.tar.gz
        phpSha256Hash: 47f0be6188b05390bb457eb1968ea19463acada79650afc35ec763348d5c2370
