ARG baseImage=datadog/dd-trace-ci:php-8.0_alpine
FROM ${baseImage} as base

RUN set -eux && \
    apk add --no-cache \
        build-base \
        cargo \
        patchelf \
        protoc \
        unzip;
