version: '3.7'

services:

  base:
    image: datadog/dd-trace-ci:alpine
    build:
      context: .
      x-bake: &bake
        platforms:
          - linux/arm64
          - linux/amd64

  php-8.0:
    image: datadog/dd-trace-ci:php-8.0_alpine
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.30.tar.gz
        phpSha256Hash: 449d2048fcb20a314d8c218097c6d1047a9f1c5bb72aa54d5d3eba0a27a4c80c
