##############################################################
# PHP 5.6
FROM alpine:3.4 AS php.5.6.alpine.3.4
RUN apk --no-cache add 'php5=5.6.36-r0'

FROM alpine:3.5 AS php.5.6.alpine.3.5
RUN apk --no-cache add 'php5=5.6.38-r0'

FROM alpine:3.6 AS php.5.6.alpine.3.6
RUN apk --no-cache add 'php5=5.6.40-r0'

FROM alpine:3.7 AS php.5.6.alpine.3.7
RUN apk --no-cache add 'php5=5.6.40-r0'

FROM alpine:3.8 AS php.5.6.alpine.3.8
RUN apk --no-cache add 'php5=5.6.40-r0'

##############################################################
# PHP 7.0
FROM alpine:3.5 AS php.7.0.alpine.3.5
RUN apk --no-cache add 'php7=7.0.33-r0'

##############################################################
# PHP 7.1
FROM alpine:3.6 AS php.7.1.alpine.3.6
RUN apk --no-cache add 'php7=7.1.17-r0'

FROM alpine:3.7 AS php.7.1.alpine.3.7
RUN apk --no-cache add 'php7=7.1.33-r0'

##############################################################
# PHP 7.2
FROM alpine:3.8 AS php.7.2.alpine.3.8
RUN apk --no-cache add 'php7=7.2.26-r0'

FROM alpine:3.9 AS php.7.2.alpine.3.9
RUN apk --no-cache add 'php7=7.2.27-r0'

##############################################################
# PHP 7.3
FROM alpine:3.10 AS php.7.3.alpine.3.10
RUN apk --no-cache add 'php7=7.3.14-r0'

FROM alpine:3.11 AS php.7.3.alpine.3.11
RUN apk --no-cache add 'php7=7.3.14-r0'
