version: "3.6"

services:
  flow:
    depends_on: ['mysql', 'nginx_file_server']
    image: 'datadog/dd-trace-ci:php-framework-flow'
    build:
      context: contrib
      target: flow
    ulimits:
      core: 99999999999
    cap_add:
      - SYS_PTRACE
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_HOST: "%"
    expose: ["3306"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx_file_server:
    build: nginx_file_server
    expose: ["80"]
