version: "3.6"

services:

  phpredis4:
    depends_on:
      - nginx_file_server
      - redis
    environment:
      - REDIS_HOST=redis
    image: datadog/dd-trace-ci:php-framework-phpredis-4
    build:
      context: contrib
      target: phpredis
      args:
        - PHPREDIS_VERSION_TAG=4.3.0
    ulimits:
      core: 99999999999
    cap_add:
      - SYS_PTRACE

  redis:
    image: datadog/dd-trace-ci:php-redis-5.0

  nginx_file_server:
    build: nginx_file_server
    expose: ["80"]
