version: "3.6"

services:
  symfony:
    depends_on: ['redis', 'redis_cluster', 'nginx_file_server', 'memcached']
    environment:
      - "REDIS_HOST=redis"
      - "MEMCACHED_HOST=memcached"
      - "REDIS_CLUSTER_HOSTS=redis_cluster:7000 redis_cluster:7001 redis_cluster:7002 redis_cluster:7003 redis_cluster:7004 redis_cluster:7005"
    image: 'datadog/dd-trace-ci:php-framework-symfony'
    build:
      context: contrib
      target: symfony
    ulimits:
      core: 99999999999
    cap_add:
      - SYS_PTRACE

  redis:
    image: redis:5.0.5
    expose:
      - 6379
  redis_cluster:
    image: grokzen/redis-cluster:5.0.5
    expose:
      - 6379
      - 7000
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
  memcached:
    image: memcached
    expose:
      - 11211

  nginx_file_server:
    build: nginx_file_server
    expose: ["80"]
