"""Locked libdatadog path crates reachable from dd-trace-php products.

Generated from the pinned Cargo metadata at libdatadog 817cf820879a76fdd8eeb3ecb47e04e8f8ecbd6c.
"""

def rust_workspace_target_name(package):
    return "rust_" + package.replace("/", "_").replace("-", "_")

LIBDATADOG_CRATES = [
    struct(
        package = "libdatadog/libdd-alloc",
        source_dir = "libdd-alloc",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.0.0",
        has_build_script = False,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/datadog-sidecar",
        source_dir = "datadog-sidecar",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.0.1",
        has_build_script = False,
        declared_features = ["default", "stats-obfuscation", "tokio-console", "tracing"],
    ),
    struct(
        package = "libdatadog/datadog-sidecar-ffi",
        source_dir = "datadog-sidecar-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.0.1",
        has_build_script = True,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/datadog-sidecar-macros",
        source_dir = "datadog-sidecar-macros",
        crate_root = "src/lib.rs",
        proc_macro = True,
        version = "0.0.1",
        has_build_script = False,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/libdd-capabilities",
        source_dir = "libdd-capabilities",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "3.0.1",
        has_build_script = False,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/libdd-capabilities-impl",
        source_dir = "libdd-capabilities-impl",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "5.0.0",
        has_build_script = False,
        declared_features = ["default", "fips", "https"],
    ),
    struct(
        package = "libdatadog/libdd-common",
        source_dir = "libdd-common",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "6.0.0",
        has_build_script = False,
        declared_features = ["bench-utils", "cgroup_testing", "default", "fips", "http-client", "https", "hyper-proxy", "regex-lite", "require-regex-full", "reqwest", "test-utils", "tls-core", "use_webpki_roots"],
    ),
    struct(
        package = "libdatadog/libdd-common-ffi",
        source_dir = "libdd-common-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "44.0.0",
        has_build_script = True,
        declared_features = ["cbindgen", "default", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-crashtracker",
        source_dir = "libdd-crashtracker",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "3.0.0",
        has_build_script = True,
        declared_features = ["benchmarking", "collector", "collector_windows", "cxx", "default", "generate-unit-test-files", "receiver"],
    ),
    struct(
        package = "libdatadog/libdd-crashtracker-ffi",
        source_dir = "libdd-crashtracker-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "44.0.0",
        has_build_script = True,
        declared_features = ["cbindgen", "collector", "collector_windows", "default", "demangler", "receiver", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-data-pipeline",
        source_dir = "libdd-data-pipeline",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "10.0.0",
        has_build_script = False,
        declared_features = ["compression", "default", "fips", "https", "regex-lite", "stats-obfuscation", "telemetry", "test-utils"],
    ),
    struct(
        package = "libdatadog/libdd-data-pipeline-core",
        source_dir = "libdd-data-pipeline-core",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.0.0",
        has_build_script = False,
        declared_features = ["compression", "default", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-ddsketch",
        source_dir = "libdd-ddsketch",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.1.1",
        has_build_script = True,
        declared_features = ["generate-protobuf"],
    ),
    struct(
        package = "libdatadog/libdd-dogstatsd-client",
        source_dir = "libdd-dogstatsd-client",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "6.0.0",
        has_build_script = False,
        declared_features = ["default", "fips", "https", "shared-runtime"],
    ),
    struct(
        package = "libdatadog/libdd-ffe",
        source_dir = "libdd-ffe",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "2.0.0",
        has_build_script = False,
        declared_features = ["default", "evaluation-metrics", "exposure-events", "flagevaluation-evp", "pyo3", "remote-config"],
    ),
    struct(
        package = "libdatadog/libdd-gotter",
        source_dir = "libdd-gotter",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.1.0",
        has_build_script = False,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/libdd-ipc",
        source_dir = "libdd-ipc",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "2.0.0",
        has_build_script = True,
        declared_features = ["one_way_shm_futex", "tiny-bytes"],
    ),
    struct(
        package = "libdatadog/libdd-ipc-macros",
        source_dir = "libdd-ipc-macros",
        crate_root = "src/lib.rs",
        proc_macro = True,
        version = "1.0.1",
        has_build_script = False,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/libdd-library-config",
        source_dir = "libdd-library-config",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "4.0.0",
        has_build_script = False,
        declared_features = ["default", "otel-thread-ctx", "process-context-reader", "process-context-writer"],
    ),
    struct(
        package = "libdatadog/libdd-library-config-ffi",
        source_dir = "libdd-library-config-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.0.2",
        has_build_script = True,
        declared_features = ["catch_panic", "cbindgen", "default", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-live-debugger",
        source_dir = "libdd-live-debugger",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.0.0",
        has_build_script = False,
        declared_features = ["regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-live-debugger-ffi",
        source_dir = "libdd-live-debugger-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.0.1",
        has_build_script = True,
        declared_features = ["cbindgen", "default", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-profiling",
        source_dir = "libdd-profiling",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.0.0",
        has_build_script = False,
        declared_features = ["cxx", "default", "test-utils"],
    ),
    struct(
        package = "libdatadog/libdd-profiling-protobuf",
        source_dir = "libdd-profiling-protobuf",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "2.0.0",
        has_build_script = False,
        declared_features = ["bolero", "prost_impls"],
    ),
    struct(
        package = "libdatadog/libdd-remote-config",
        source_dir = "libdd-remote-config",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "5.0.0",
        has_build_script = False,
        declared_features = ["agentless", "client", "default", "fips", "https", "regex-lite", "test"],
    ),
    struct(
        package = "libdatadog/libdd-shared-runtime",
        source_dir = "libdd-shared-runtime",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "4.0.0",
        has_build_script = False,
        declared_features = ["default", "fips", "https", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-telemetry",
        source_dir = "libdd-telemetry",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "8.0.0",
        has_build_script = False,
        declared_features = ["default", "fips", "https", "tracing"],
    ),
    struct(
        package = "libdatadog/libdd-telemetry-ffi",
        source_dir = "libdd-telemetry-ffi",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "44.0.0",
        has_build_script = True,
        declared_features = ["cbindgen", "default", "expanded_builder_macros", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-tinybytes",
        source_dir = "libdd-tinybytes",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "1.1.3",
        has_build_script = False,
        # Cargo exposes an implicit `serde` feature for the optional dependency;
        # `serialization = ["serde"]` enables it in the production unit graph.
        declared_features = ["bytes_string", "serde", "serialization"],
    ),
    struct(
        package = "libdatadog/libdd-trace-normalization",
        source_dir = "libdd-trace-normalization",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "4.0.0",
        has_build_script = False,
        declared_features = ["fuzzing"],
    ),
    struct(
        package = "libdatadog/libdd-trace-obfuscation",
        source_dir = "libdd-trace-obfuscation",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "8.0.0",
        has_build_script = False,
        declared_features = ["default", "fips", "https", "regex-lite"],
    ),
    struct(
        package = "libdatadog/libdd-trace-protobuf",
        source_dir = "libdd-trace-protobuf",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "5.0.0",
        has_build_script = True,
        declared_features = ["fuzzing", "generate-protobuf"],
    ),
    struct(
        package = "libdatadog/libdd-trace-stats",
        source_dir = "libdd-trace-stats",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "9.0.0",
        has_build_script = False,
        declared_features = ["compression", "default", "dogstatsd", "fips", "https", "stats-obfuscation", "telemetry"],
    ),
    struct(
        package = "libdatadog/libdd-trace-utils",
        source_dir = "libdd-trace-utils",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "12.0.0",
        has_build_script = False,
        declared_features = ["bench-internals", "change-buffer", "compression", "default", "fips", "https", "mini_agent", "test-utils", "zstd"],
    ),
    struct(
        package = "libdatadog/spawn_worker",
        source_dir = "spawn_worker",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.0.1",
        has_build_script = True,
        declared_features = [],
    ),
    struct(
        package = "libdatadog/tools/sidecar_mockgen",
        source_dir = "tools/sidecar_mockgen",
        crate_root = "src/lib.rs",
        proc_macro = False,
        version = "0.1.0",
        has_build_script = False,
        declared_features = [],
    ),
]
