FROM centos:8

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
RUN dnf module install -y php:remi-7.2

RUN yum update -y \
    && yum install -y \
        wget \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN dnf install -y httpd httpd-tools

RUN wget -O dd-trace-php.rpm \
    https://github.com/DataDog/dd-trace-php/releases/download/0.41.1/datadog-php-tracer-0.41.1-1.x86_64.rpm \
    && rpm -ivh dd-trace-php.rpm

RUN mkdir -p /run/php-fpm && touch /run/php-fpm/www.sock

ADD www.conf /etc/php-fpm.d/www.conf
ADD virtual-host.conf /etc/httpd/conf.d/virtual-host.conf
ADD index.php /var/www/html/index.php

CMD bash
