FROM nginx:1.17

ADD ./dockerfiles/default.conf.template /etc/nginx/conf.d/default.conf.template
ADD ./Laravel57 /var/www

# Add dd-doctor.php
ADD https://raw.githubusercontent.com/DataDog/dd-trace-php/master/src/dd-doctor.php /var/www/public/dd-doctor.php
ENV NGINX_PORT=80
ENV NGINX_FPM_PASS=localhost:9000
CMD ["/bin/bash", "-c", "envsubst '$NGINX_FPM_PASS $NGINX_PORT' < /etc/nginx/conf.d/default.conf.template | tee /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
