FROM php:7.2-fpm AS base

RUN apt update \
    && apt install -y \
    gdb \
    git \
    less \
    libcurl4-gnutls-dev \
    libfcgi0ldbl \
    procps \
    sudo \
    time \
    unzip \
    vim \
    && pecl install xdebug \
    && docker-php-ext-install opcache \
    && rm -rf /var/lib/apt/lists/*

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php  --install-dir="/usr/bin" --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && composer self-update

WORKDIR /var/www

# Add dd-doctor.php
ADD https://raw.githubusercontent.com/DataDog/dd-trace-php/master/src/dd-doctor.php /var/www/public/dd-doctor.php

ADD ./tests/overhead/Laravel57 /var/www
RUN chmod -R 777 bootstrap storage
RUN composer install

ADD ./tests/overhead/dockerfiles/www.conf /usr/local/etc/php-fpm.d/www.conf
ADD ./tests/overhead/dockerfiles/php-fpm.conf /usr/local/etc/php-fpm.conf
ADD ./tests/overhead/dockerfiles/99-ddtrace-custom.ini /usr/local/etc/php/conf.d/99-ddtrace-custom.ini
ADD ./tests/overhead/dockerfiles/opcache.ini /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini



########################################################################################################################

FROM base AS notracer

ADD ./tests/overhead/dockerfiles/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.profiler_output_name=callgrind.%t.notracer" >> /usr/local/etc/php/conf.d/xdebug.ini



########################################################################################################################

FROM base AS master

RUN git clone https://github.com/DataDog/dd-trace-php.git \
    --single-branch \
    --branch master \
    --depth 1 \
    /dd-trace-php

WORKDIR /dd-trace-php

RUN composer install-ext
RUN echo "ddtrace.request_init_hook=/dd-trace-php/bridge/dd_wrap_autoloader.php" >> /usr/local/etc/php/conf.d/ddtrace.ini

ADD ./tests/overhead/dockerfiles/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.profiler_output_name=callgrind.%t.master" >> /usr/local/etc/php/conf.d/xdebug.ini



########################################################################################################################

FROM base AS head

ADD ./ /dd-trace-php

WORKDIR /dd-trace-php

RUN composer install-ext
RUN echo "ddtrace.request_init_hook=/dd-trace-php/bridge/dd_wrap_autoloader.php" >> /usr/local/etc/php/conf.d/ddtrace.ini

ADD ./tests/overhead/dockerfiles/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.profiler_output_name=callgrind.%t.head" >> /usr/local/etc/php/conf.d/xdebug.ini



########################################################################################################################

FROM base AS release

ARG DD_TRACE_LIBRARY_VERSION

# Install DDTrace deb
ADD https://github.com/DataDog/dd-trace-php/releases/download/${DD_TRACE_LIBRARY_VERSION}/datadog-php-tracer_${DD_TRACE_LIBRARY_VERSION}_amd64.deb datadog-php-tracer.deb
RUN dpkg -i datadog-php-tracer.deb

WORKDIR /var/www

ADD ./tests/overhead/dockerfiles/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.profiler_output_name=callgrind.%t.release" >> /usr/local/etc/php/conf.d/xdebug.ini
