blank_issues_enabled: false
contact_links:
  - name: Bug Report (Helpdesk)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:apm&tf_1900004146284=pt_apm_language:php
    about: Create a private Bug Report via the helpdesk (no login required). This will allow us to look up your account and allows you to provide additional information in private.
  - name: Feature Request (Helpdesk)
    url: https://help.datadoghq.com/hc/en-us/requests/new?tf_1260824651490=pt_product_type:apm&tf_1900004146284=pt_apm_language:php&tf_1260825272270=pt_apm_category_feature_request
    about: Create a private Feature Request via the helpdesk (no login required). This helps with prioritization and allows you to provide additional information in private.
