blank_issues_enabled: true
contact_links:
  - name: Check the docs
    url: https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/php/
    about: In case you need help with setup and configuration you might find help in the offical documentation
