RESULTS_DIR := ./.results

test.scenario.%: results.scenario.%
	@docker-compose up --remove-orphan $(*)

results.scenario.%:
	@mkdir -p $(RESULTS_DIR)/$(*)
	@chmod -R a+w $(RESULTS_DIR)/$(*)

shell.scenario.%:
	@docker-compose run --rm $(*) bash

# Dynamically generated targets will be added after this line
