up:
	@docker-compose up -d agent redis httpbin memcached elasticsearch mysql

clean_results:
	@rm -rf ./.results/*
	@echo "Results folder cleaned"

test.scenario.%:
	@docker-compose up --remove-orphan $(*)

# Dynamically generated targets will be added after this line
