#include "handlers_internal.h"

void ddtrace_phpredis_handlers_startup(void) {
    // clang-format off
    ddtrace_string methods[] = {
        DDTRACE_STRING_LITERAL("__construct"),
        DDTRACE_STRING_LITERAL("append"),
        DDTRACE_STRING_LITERAL("auth"),
        DDTRACE_STRING_LITERAL("bgrewriteaof"),
        DDTRACE_STRING_LITERAL("bgsave"),
        DDTRACE_STRING_LITERAL("close"),
        DDTRACE_STRING_LITERAL("connect"),
        DDTRACE_STRING_LITERAL("decr"),
        DDTRACE_STRING_LITERAL("decrby"),
        DDTRACE_STRING_LITERAL("del"),
        DDTRACE_STRING_LITERAL("delete"),
        DDTRACE_STRING_LITERAL("dump"),
        DDTRACE_STRING_LITERAL("echo"),
        DDTRACE_STRING_LITERAL("exists"),
        DDTRACE_STRING_LITERAL("expire"),
        DDTRACE_STRING_LITERAL("expireat"),
        DDTRACE_STRING_LITERAL("flushall"),
        DDTRACE_STRING_LITERAL("flushdb"),
        DDTRACE_STRING_LITERAL("get"),
        DDTRACE_STRING_LITERAL("getbit"),
        DDTRACE_STRING_LITERAL("getkeys"),
        DDTRACE_STRING_LITERAL("getmultiple"),
        DDTRACE_STRING_LITERAL("getrange"),
        DDTRACE_STRING_LITERAL("getset"),
        DDTRACE_STRING_LITERAL("incr"),
        DDTRACE_STRING_LITERAL("incrby"),
        DDTRACE_STRING_LITERAL("incrbyfloat"),
        DDTRACE_STRING_LITERAL("keys"),
        DDTRACE_STRING_LITERAL("mget"),
        DDTRACE_STRING_LITERAL("migrate"),
        DDTRACE_STRING_LITERAL("move"),
        DDTRACE_STRING_LITERAL("mset"),
        DDTRACE_STRING_LITERAL("msetnx"),
        DDTRACE_STRING_LITERAL("object"),
        DDTRACE_STRING_LITERAL("open"),
        DDTRACE_STRING_LITERAL("pconnect"),
        DDTRACE_STRING_LITERAL("persist"),
        DDTRACE_STRING_LITERAL("pexpire"),
        DDTRACE_STRING_LITERAL("pexpireat"),
        DDTRACE_STRING_LITERAL("ping"),
        DDTRACE_STRING_LITERAL("popen"),
        DDTRACE_STRING_LITERAL("psetex"),
        DDTRACE_STRING_LITERAL("pttl"),
        DDTRACE_STRING_LITERAL("randomkey"),
        DDTRACE_STRING_LITERAL("rename"),
        DDTRACE_STRING_LITERAL("renamekey"),
        DDTRACE_STRING_LITERAL("renamenx"),
        DDTRACE_STRING_LITERAL("restore"),
        DDTRACE_STRING_LITERAL("save"),
        DDTRACE_STRING_LITERAL("scan"),
        DDTRACE_STRING_LITERAL("select"),
        DDTRACE_STRING_LITERAL("set"),
        DDTRACE_STRING_LITERAL("setbit"),
        DDTRACE_STRING_LITERAL("setex"),
        DDTRACE_STRING_LITERAL("setnx"),
        DDTRACE_STRING_LITERAL("setrange"),
        DDTRACE_STRING_LITERAL("settimeout"),
        DDTRACE_STRING_LITERAL("swapdb"),
        DDTRACE_STRING_LITERAL("sort"),
        DDTRACE_STRING_LITERAL("strlen"),
        DDTRACE_STRING_LITERAL("ttl"),
        DDTRACE_STRING_LITERAL("type"),

        // Hash functions
        DDTRACE_STRING_LITERAL("hdel"),
        DDTRACE_STRING_LITERAL("hexists"),
        DDTRACE_STRING_LITERAL("hget"),
        DDTRACE_STRING_LITERAL("hgetall"),
        DDTRACE_STRING_LITERAL("hincrby"),
        DDTRACE_STRING_LITERAL("hincrbyfloat"),
        DDTRACE_STRING_LITERAL("hkeys"),
        DDTRACE_STRING_LITERAL("hlen"),
        DDTRACE_STRING_LITERAL("hmget"),
        DDTRACE_STRING_LITERAL("hmset"),
        DDTRACE_STRING_LITERAL("hscan"),
        DDTRACE_STRING_LITERAL("hset"),
        DDTRACE_STRING_LITERAL("hsetnx"),
        DDTRACE_STRING_LITERAL("hstrlen"),
        DDTRACE_STRING_LITERAL("hvals"),

        // Lists
        DDTRACE_STRING_LITERAL("blpop"),
        DDTRACE_STRING_LITERAL("brpop"),
        DDTRACE_STRING_LITERAL("brpoplpush"),
        DDTRACE_STRING_LITERAL("lget"),
        DDTRACE_STRING_LITERAL("lgetrange"),
        DDTRACE_STRING_LITERAL("lindex"),
        DDTRACE_STRING_LITERAL("linsert"),
        DDTRACE_STRING_LITERAL("listtrim"),
        DDTRACE_STRING_LITERAL("llen"),
        DDTRACE_STRING_LITERAL("lpop"),
        DDTRACE_STRING_LITERAL("lpush"),
        DDTRACE_STRING_LITERAL("lpushx"),
        DDTRACE_STRING_LITERAL("lrange"),
        DDTRACE_STRING_LITERAL("lrem"),
        DDTRACE_STRING_LITERAL("lremove"),
        DDTRACE_STRING_LITERAL("lset"),
        DDTRACE_STRING_LITERAL("lsize"),
        DDTRACE_STRING_LITERAL("ltrim"),
        DDTRACE_STRING_LITERAL("rpop"),
        DDTRACE_STRING_LITERAL("rpoplpush"),
        DDTRACE_STRING_LITERAL("rpush"),
        DDTRACE_STRING_LITERAL("rpushx"),

        // Sets
        DDTRACE_STRING_LITERAL("sadd"),
        DDTRACE_STRING_LITERAL("scard"),
        DDTRACE_STRING_LITERAL("scontains"),
        DDTRACE_STRING_LITERAL("sdiff"),
        DDTRACE_STRING_LITERAL("sdiffstore"),
        DDTRACE_STRING_LITERAL("sgetmembers"),
        DDTRACE_STRING_LITERAL("sinter"),
        DDTRACE_STRING_LITERAL("sinterstore"),
        DDTRACE_STRING_LITERAL("sismember"),
        DDTRACE_STRING_LITERAL("smembers"),
        DDTRACE_STRING_LITERAL("smove"),
        DDTRACE_STRING_LITERAL("spop"),
        DDTRACE_STRING_LITERAL("srandmember"),
        DDTRACE_STRING_LITERAL("srem"),
        DDTRACE_STRING_LITERAL("sremove"),
        DDTRACE_STRING_LITERAL("sscan"),
        DDTRACE_STRING_LITERAL("ssize"),
        DDTRACE_STRING_LITERAL("sunion"),
        DDTRACE_STRING_LITERAL("sunionstore"),

        // Sorted Sets
        DDTRACE_STRING_LITERAL("zadd"),
        DDTRACE_STRING_LITERAL("zcard"),
        DDTRACE_STRING_LITERAL("zsize"),
        DDTRACE_STRING_LITERAL("zcount"),
        DDTRACE_STRING_LITERAL("zincrby"),
        DDTRACE_STRING_LITERAL("zinter"),
        DDTRACE_STRING_LITERAL("zrange"),
        DDTRACE_STRING_LITERAL("zrangebyscore"),
        DDTRACE_STRING_LITERAL("zrevrangebyscore"),
        DDTRACE_STRING_LITERAL("zrangebylex"),
        DDTRACE_STRING_LITERAL("zrank"),
        DDTRACE_STRING_LITERAL("zrevrank"),
        DDTRACE_STRING_LITERAL("zpopmax"),
        DDTRACE_STRING_LITERAL("zpopmin"),
        DDTRACE_STRING_LITERAL("zrem"),
        DDTRACE_STRING_LITERAL("zremove"),
        DDTRACE_STRING_LITERAL("zdelete"),
        DDTRACE_STRING_LITERAL("zremrangebyrank"),
        DDTRACE_STRING_LITERAL("zdeleterangebyrank"),
        DDTRACE_STRING_LITERAL("zremrangebyscore"),
        DDTRACE_STRING_LITERAL("zdeleterangebyscore"),
        DDTRACE_STRING_LITERAL("zremoverangebyscore"),
        DDTRACE_STRING_LITERAL("zrevrange"),
        DDTRACE_STRING_LITERAL("zscore"),
        DDTRACE_STRING_LITERAL("zunion"),
        DDTRACE_STRING_LITERAL("zunionstore"),
        DDTRACE_STRING_LITERAL("zscan"),

        // Pub/Sub
        DDTRACE_STRING_LITERAL("publish"),

        // Transactions
        DDTRACE_STRING_LITERAL("multi"),
        DDTRACE_STRING_LITERAL("exec"),

        // Raw command
        DDTRACE_STRING_LITERAL("rawcommand"),

        // Scripting
        DDTRACE_STRING_LITERAL("eval"),
        DDTRACE_STRING_LITERAL("evalsha"),
        DDTRACE_STRING_LITERAL("script"),
        DDTRACE_STRING_LITERAL("getlasterror"),
        DDTRACE_STRING_LITERAL("clearlasterror"),
        DDTRACE_STRING_LITERAL("_unserialize"),
        DDTRACE_STRING_LITERAL("_serialize"),

        // Introspections
        DDTRACE_STRING_LITERAL("isconnected"),
        DDTRACE_STRING_LITERAL("gethost"),
        DDTRACE_STRING_LITERAL("getport"),
        DDTRACE_STRING_LITERAL("getdbnum"),
        DDTRACE_STRING_LITERAL("gettimeout"),
        DDTRACE_STRING_LITERAL("getreadtimeout"),

        // Geocoding"
        DDTRACE_STRING_LITERAL("geoadd"),
        DDTRACE_STRING_LITERAL("geohash"),
        DDTRACE_STRING_LITERAL("geopos"),
        DDTRACE_STRING_LITERAL("geodist"),
        DDTRACE_STRING_LITERAL("georadius"),
        DDTRACE_STRING_LITERAL("georadiusbymember"),

        // Streams
        DDTRACE_STRING_LITERAL("xack"),
        DDTRACE_STRING_LITERAL("xadd"),
        DDTRACE_STRING_LITERAL("xclaim"),
        DDTRACE_STRING_LITERAL("xdel"),
        DDTRACE_STRING_LITERAL("xgroup"),
        DDTRACE_STRING_LITERAL("xinfo"),
        DDTRACE_STRING_LITERAL("xlen"),
        DDTRACE_STRING_LITERAL("xpending"),
        DDTRACE_STRING_LITERAL("xrange"),
        DDTRACE_STRING_LITERAL("xread"),
        DDTRACE_STRING_LITERAL("xreadgroup"),
        DDTRACE_STRING_LITERAL("xrevrange"),
        DDTRACE_STRING_LITERAL("xtrim"),
    };
    // clang-format on

    ddtrace_string phpredis = DDTRACE_STRING_LITERAL("redis");
    ddtrace_string phpredis_cluster = DDTRACE_STRING_LITERAL("rediscluster");
    size_t methods_len = sizeof methods / sizeof methods[0];
    ddtrace_replace_internal_methods(phpredis, methods_len, methods);
    ddtrace_replace_internal_methods(phpredis_cluster, methods_len, methods);
}
