#ifndef DD_CONFIGURATION_DEFINITIONS_H
#define DD_CONFIGURATION_DEFINITIONS_H

#define DD_CONFIGURATION CHAR(get_dd_agent_host, "DD_AGENT_HOST", "localhost")

#endif  // DD_CONFIGURATION_DEFINITIONS_H
