"""Public PHP bridge generation macro."""

load(":bridge_files.bzl", "bridge_files")

# The configured PHP SDK is supplied by product targets.  This macro keeps the
# four historical bridge compilation operations ordered and individually
# declared without making Composer or a target PHP executable an action input.
def php_bridge_files(name):
    bridge_files(
        name = name,
        api_config = "//:src/bridge/_files_api.php",
        openfeature_config = "//:src/bridge/_files_openfeature.php",
        opentelemetry_config = "//:src/bridge/_files_opentelemetry.php",
        source_files = [
            "//:src/api/Type.php",
            "//:src/api/Tag.php",
            "//:src/api/Http/Urls.php",
            "//:src/api/Contracts/Tracer.php",
            "//:src/api/Contracts/Span.php",
            "//:src/api/Contracts/Scope.php",
            "//:src/api/Contracts/ScopeManager.php",
            "//:src/api/Contracts/SpanContext.php",
            "//:src/api/Data/SpanContext.php",
            "//:src/api/Data/Span.php",
            "//:src/api/Sampling/PrioritySampling.php",
            "//:src/api/Transport.php",
            "//:src/api/Obfuscation/WildcardToRegex.php",
            "//:src/api/Reference.php",
            "//:src/api/Exceptions/InvalidReferenceArgument.php",
            "//:src/api/Exceptions/UnsupportedFormat.php",
            "//:src/api/Exceptions/InvalidSpanArgument.php",
            "//:src/api/Exceptions/InvalidReferencesSet.php",
            "//:src/api/Exceptions/InvalidSpanOption.php",
            "//:src/api/GlobalTracer.php",
            "//:src/api/Format.php",
            "//:src/api/Log/LoggerInterface.php",
            "//:src/api/Log/InterpolateTrait.php",
            "//:src/api/Log/LogLevel.php",
            "//:src/api/Log/Logger.php",
            "//:src/api/Log/AbstractLogger.php",
            "//:src/api/Log/DatadogLogger.php",
            "//:src/api/Log/ErrorLogLogger.php",
            "//:src/api/Log/NullLogger.php",
            "//:src/api/Log/NonThrowingLogger.php",
            "//:src/api/Log/LoggingTrait.php",
            "//:src/api/StartSpanOptions.php",
            "//:src/DDTrace/SpanContext.php",
            "//:src/DDTrace/Span.php",
            "//:src/DDTrace/Time.php",
            "//:src/DDTrace/Transport/Internal.php",
            "//:src/DDTrace/Processing/TraceAnalyticsProcessor.php",
            "//:src/DDTrace/Scope.php",
            "//:src/DDTrace/Propagator.php",
            "//:src/DDTrace/Propagators/TextMap.php",
            "//:src/DDTrace/ScopeManager.php",
            "//:src/DDTrace/Tracer.php",
            "//:src/DDTrace/OpenFeature/DataDogProvider.php",
            "//:src/DDTrace/OpenTelemetry/Context.php",
            "//:src/DDTrace/OpenTelemetry/Convention.php",
            "//:src/DDTrace/OpenTelemetry/SpanContext.php",
            "//:src/DDTrace/OpenTelemetry/Span.php",
            "//:src/DDTrace/OpenTelemetry/SpanBuilder.php",
            "//:src/DDTrace/OpenTelemetry/CachedInstrumentation.php",
            "//:src/DDTrace/OpenTelemetry/CompositeResolver.php",
            "//:src/DDTrace/OpenTelemetry/Configuration.php",
            "//:src/DDTrace/OpenTelemetry/OtlpHooks.php",
            "//:src/DDTrace/OpenTelemetry/Detectors/DetectorHelper.php",
            "//:src/DDTrace/OpenTelemetry/Detectors/Environment.php",
            "//:src/DDTrace/OpenTelemetry/Detectors/Host.php",
            "//:src/DDTrace/OpenTelemetry/Detectors/Service.php",
        ],
        tracer_config = "//:src/bridge/_files_tracer.php",
        vendor = "@php_generation_vendor//:vendor",
    )
