"""Repository setup for the locked PHP bridge generation vendor tree."""

load("//bazel/dependencies:manifest.bzl", "GENERATION_COMPOSER_PACKAGES")

_AUTOLOAD = """<?php
// Generated by the repository rule from the checked-in Composer lock.  Keep
// this intentionally small: the eight locked packages use only PSR-4 plus the
// two Symfony polyfill bootstrap files.
spl_autoload_register(function ($class) {
    $prefixes = array(
        'ClassPreloader\\\\Console\\\\' => 'classpreloader/console/src/',
        'ClassPreloader\\\\' => 'classpreloader/classpreloader/src/',
        'PhpParser\\\\' => 'nikic/php-parser/lib/PhpParser/',
        'Psr\\\\Log\\\\' => 'psr/log/Psr/Log/',
        'Symfony\\\\Component\\\\Console\\\\' => 'symfony/console/',
        'Symfony\\\\Component\\\\Debug\\\\' => 'symfony/debug/',
        'Symfony\\\\Polyfill\\\\Ctype\\\\' => 'symfony/polyfill-ctype/',
        'Symfony\\\\Polyfill\\\\Mbstring\\\\' => 'symfony/polyfill-mbstring/',
    );
    foreach ($prefixes as $prefix => $directory) {
        if (strpos($class, $prefix) === 0) {
            $path = __DIR__ . '/' . $directory . str_replace('\\\\', '/', substr($class, strlen($prefix))) . '.php';
            if (file_exists($path)) {
                require $path;
            }
            return;
        }
    }
});
// Composer registers PSR-4 class loading before running autoload.files. This
// matters when a polyfill bootstrap refers to one of its own classes.
require_once __DIR__ . '/symfony/polyfill-ctype/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
"""

def _generation_vendor_impl(rctx):
    for name in sorted(GENERATION_COMPOSER_PACKAGES.keys()):
        source = GENERATION_COMPOSER_PACKAGES[name]
        rctx.download_and_extract(
            url = source.url,
            output = "vendor/" + source.package,
            sha256 = source.sha256,
            stripPrefix = source.strip_prefix,
            type = "zip",
        )
    rctx.file("vendor/autoload.php", _AUTOLOAD)
    rctx.file(
        "BUILD.bazel",
        """package(default_visibility = ["//visibility:public"])
filegroup(
    name = "vendor",
    srcs = glob(["vendor/**"]),
)
""",
    )
    return rctx.repo_metadata(reproducible = True)

generation_vendor_repository = repository_rule(
    implementation = _generation_vendor_impl,
)

def _generation_composer_sources_impl(mctx):
    generation_vendor_repository(name = "php_generation_vendor")
    return mctx.extension_metadata(
        reproducible = True,
        root_module_direct_deps = ["php_generation_vendor"],
        root_module_direct_dev_deps = [],
    )

generation_composer_sources = module_extension(
    implementation = _generation_composer_sources_impl,
)
