version: '3.7'

services:

  vc15-base:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-base-vc15
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vc15.Dockerfile

  vs16-base:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-base-vs16
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vs16.Dockerfile

  vs17-base:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-base-vs17
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: vs17.Dockerfile

  vc15:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-vc15
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vc15"
        sdkVersion: "2.2.0"

  vs16:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-vs16
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vs16"
        sdkVersion: "2.2.0"

  vs17:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:windows-vs17
    build:
      platforms:
        - windows/amd64
      context: .
      dockerfile: basetools.Dockerfile
      args:
        vsVersion: "vs17"
        sdkVersion: "2.3.0"

  php-8.5:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.5_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.5.7"
        vsVersion: "vs17"
        phpTarGzUrl: https://www.php.net/distributions/php-8.5.7.tar.gz
        phpSha256Hash: "e5eba93fd6dd3241d0e61e932eb99a3783b40568553fb0e511b660ecd863a049"

  php-8.4:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.4_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.4.22"
        vsVersion: "vs17"
        phpTarGzUrl: https://www.php.net/distributions/php-8.4.22.tar.gz
        phpSha256Hash: "a012c2c9724baf214a70b41b40a7e130906b8855e54268afa5bc4ae17bc9d823"

  php-8.3:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.3_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.3.31"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.3.31.tar.gz
        phpSha256Hash: "4e7baaf0a690e954a20e7ced3dd633ce8cb8094e2b6b612a55e703ecbbdcbf4f"

  php-8.2:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.2_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.2.31"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.2.31.tar.gz
        phpSha256Hash: "083c2f61cc5f527eb293c4c468a91af46a9678785957e023b2796a9db290d870"

  php-8.1:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.1_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.1.32"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.1.32.tar.gz
        phpSha256Hash: "4846836d1de27dbd28e89180f073531087029a77e98e8e019b7b2eddbdb1baff"

  php-8.0:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-8.0_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "8.0.30"
        vsVersion: "vs16"
        phpTarGzUrl: https://www.php.net/distributions/php-8.0.30.tar.gz
        phpSha256Hash: "449d2048fcb20a314d8c218097c6d1047a9f1c5bb72aa54d5d3eba0a27a4c80c"

  php-7.4:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-7.4_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.4.33"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.4.33.tar.gz
        phpSha256Hash: 5a2337996f07c8a097e03d46263b5c98d2c8e355227756351421003bea8f463e

  php-7.3:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-7.3_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.3.33"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.3.33.tar.gz
        phpSha256Hash: 9a369c32c6f52036b0a890f290327f148a1904ee66aa56e2c9a7546da6525ec8

  php-7.2:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-7.2_windows
    build:
      platforms:
        - windows/amd64
      context: .
      args:
        phpVersion: "7.2.34"
        vsVersion: "vc15"
        phpTarGzUrl: https://www.php.net/distributions/php-7.2.34.tar.gz
        phpSha256Hash: 8b2777c741e83f188d3ca6d8e98ece7264acafee86787298fae57e05d0dddc78
