# VS 2026 (vs18): PHP 8.6 official Windows builds use it. The .NET Framework 4.8
# runtime base is what Microsoft documents for Build Tools containers.
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019

ADD https://aka.ms/vs/18/stable/vs_buildtools.exe /tmp/vs_buildtools.exe
# The MSVC toolset version is not pinned (VC.Tools.x86.x64 installs the latest one), hence the
# wildcards. 3010 means "reboot required" and is fine in a container.
RUN powershell "cmd /S /C /tmp/vs_buildtools.exe --quiet --wait --norestart --nocache --installPath 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools' --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest --add Microsoft.VisualStudio.Component.VC.CoreBuildTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.26100; $rc = $LASTEXITCODE; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\*\bin\Hostx86'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\*\lib\onecore'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Tools\MSVC\*\lib\x86'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\arm64'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x86'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\arm64'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x86'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\arm64'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x86'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Testing'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\cppwinrt\'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\winrt\'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Program Files (x86)\Windows Kits\10\References'; Remove-Item -Recurse -ErrorAction SilentlyContinue 'C:\Users\ContainerAdministrator\AppData\Local\Temp\*'; if ($rc -ne 0 -and $rc -ne 3010) { exit $rc }; exit 0"
RUN powershell "$ErrorActionPreference = 'Stop'; $vcvars = 'C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat'; if (-not (Test-Path $vcvars)) { Write-Error ('vcvarsall.bat not found at ' + $vcvars); exit 3 }; $q = [char]34; $cmd = 'call ' + $q + $vcvars + $q + ' amd64 >NUL && where cl.exe && where link.exe && cl.exe'; cmd /S /C $cmd; if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }"
