<?php

/**
 * Generates the CI image build + publish GitLab child pipeline.
 *
 * Source of truth (NO duplication):
 *   - dockerfiles/ci/<os>/docker-compose.yml : service name -> image:TAG
 *   - dockerfiles/ci/bookworm/.env           : $BOOKWORM_NEXT_VERSION etc.
 *
 * The compose service name is the `docker buildx bake` target and the build
 * matrix value; the `image:` tag (with env vars resolved) is the published tag.
 * This script prints a literal preamble (stages, job templates), then loops
 * over the parsed compose services to emit, per Linux OS, one build matrix job
 * over PHP versions (bake builds and pushes the multi-arch image) plus a manual
 * publish matrix job that mirrors the tags to Docker Hub. Windows is emitted the
 * same way but single-arch (no manifest) with its own build runner/script.
 */

$root = dirname(__DIR__);

// Load KEY=VALUE pairs from a .env file (used by substitute()).
function parse_env(string $path): array
{
    $env = [];
    foreach (@file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {
        if (preg_match('/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/', $line, $m)) {
            $env[$m[1]] = $m[2];
        }
    }
    return $env;
}

function substitute(string $s, array $env): string
{
    return preg_replace_callback('/\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?/', function ($m) use ($env) {
        return $env[$m[1]] ?? $m[0];
    }, $s);
}

// Parse a docker-compose.yml into [service => tag], preserving file order.
function parse_compose(string $path, array $env): array
{
    $services = [];
    $cur = null;
    $inServices = false;
    foreach (file($path, FILE_IGNORE_NEW_LINES) as $line) {
        if (preg_match('/^services:\s*$/', $line)) {
            $inServices = true;
            continue;
        }
        if (!$inServices) {
            continue;
        }
        if (preg_match('/^\S/', $line)) { // back to a top-level key
            $inServices = false;
            continue;
        }
        if (preg_match('/^  ([A-Za-z0-9][A-Za-z0-9._-]*):\s*$/', $line, $m)) {
            $cur = $m[1];
            $services[$cur] = null;
            continue;
        }
        // image: ${CI_REGISTRY_IMAGE:-...}:TAG   (first image: wins per service)
        if ($cur !== null && $services[$cur] === null
            && preg_match('/^    image:\s*[\'"]?\$\{[^}]+\}:([^\s\'"]+)/', $line, $m)) {
            $services[$cur] = substitute($m[1], $env);
        }
    }
    return array_filter($services, fn($v) => $v !== null);
}

$dirs = [
    "Bookworm" => "dockerfiles/ci/bookworm",
    "CentOS"   => "dockerfiles/ci/centos/7",
    "Alpine"   => "dockerfiles/ci/alpine_compile_extension",
];

$osList = [];
foreach ($dirs as $os => $dir) {
    $services = parse_compose("$root/$dir/docker-compose.yml", parse_env("$root/$dir/.env"));
    if (!$services) {
        fwrite(STDERR, "WARNING: no services parsed for $os ($dir)\n");
        continue;
    }
    $osList[] = ["name" => $os, "dir" => $dir, "services" => $services];
}

// Windows is single-arch (no multi-arch manifest) and uses a different build
// runner/script, so it is emitted separately from the Linux loop below. It has
// no .env, so tags resolve with an empty env map.
$winServices = parse_compose("$root/dockerfiles/ci/windows/docker-compose.yml", []);
if (!$winServices) {
    fwrite(STDERR, "WARNING: no services parsed for Windows\n");
}
?>
# CI image build + publish child pipeline, generated by
# .gitlab/generate-ci-images.php from the docker-compose.yml + .env files.
# Edit the generator, never this generated file. Windows is generated too
# (single-arch, no multi-arch manifest, different build runner/script).

stages:
  - ci-build
  - ci-publish

variables:
  CI_REGISTRY_IMAGE: "registry.ddbuild.io/ci/dd-trace-php/dd-trace-ci"

.linux_image_build:
  stage: ci-build
  rules:
    - when: manual
      allow_failure: true
  needs: []
  timeout: 4h
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:29.4.0-noble
  variables:
    DDCI_CONFIGURE_OTEL_EXPORTER: "true"
    # Compile runs on the buildx "ci" builder instance, not this job pod, so the
    # pod uses cluster defaults. MAKE_JOBS sets the builder's compile parallelism.
    MAKE_JOBS: "8"

.image_publish:
  stage: ci-publish
  rules:
    - when: manual
      allow_failure: true
  # No deps: a publish just mirrors whatever already exists in
  # registry.ddbuild.io to Docker Hub, so it can run without (re)building.
  needs: []
  trigger:
    project: DataDog/public-images
    branch: main
  # $TAG is supplied per matrix entry by the generated publish jobs.
  variables:
    IMG_REGISTRIES: "dockerhub"
    IMG_SIGNING: false
    IMG_SOURCES: "${CI_REGISTRY_IMAGE}:${TAG}"
    IMG_DESTINATIONS: "dd-trace-ci:${TAG}"

.windows_image_build:
  stage: ci-build
  rules:
    - when: manual
      allow_failure: true
  needs: []
  timeout: 6h
  tags: ["windows-v2:2019"]
  id_tokens:
    CI_IDENTITIES_GITLAB_ID_TOKEN:
      aud: ci-identities
  variables:
    DDCI_CONFIGURE_OTEL_EXPORTER: "true"
    GIT_STRATEGY: none
  script: |
    # Kill leftover containers; a previous run may still hold php_ddtrace.dll open.
    $containers = docker ps -aq 2>$null
    if ($containers) { docker rm -f $containers 2>$null }

    # Use cmd.exe rd from the parent dir: handles junctions/symlinks that PS5.1 Remove-Item cannot.
    Write-Host "Performing workspace cleanup..."
    $workspace = $PWD.Path
    Push-Location ..
    cmd /c "rd /s /q ""$workspace"""
    if (-not (Test-Path $workspace)) {
        New-Item -ItemType Directory -Path $workspace -Force | Out-Null
    }
    Pop-Location
    $remaining = Get-ChildItem -Path . -Force -ErrorAction SilentlyContinue
    if ($remaining) { Write-Host "WARNING: could not remove: $($remaining.Name -join ', ')" }
    Write-Host "Cleanup complete."

    # PS 5.1 ignores $PSNativeCommandUseErrorActionPreference; use $LASTEXITCODE checks instead.
    $ErrorActionPreference = 'Stop'

    Write-Host "Cloning repository..."
    git config --global core.longpaths true
    git config --global core.symlinks true
    git clone --branch $env:CI_COMMIT_REF_NAME $env:CI_REPOSITORY_URL .
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: git clone failed. Remaining workspace contents:"
        Get-ChildItem -Force | Select-Object Name
        exit $LASTEXITCODE
    }
    git checkout $env:CI_COMMIT_SHA
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host "Initializing submodules..."
    git submodule update --init --recursive
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Host "Git setup complete."

    Write-Host "Downloading docker-compose..."
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $dockerCompose = "$PWD\docker-compose.exe"
    Start-BitsTransfer -Source "https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-windows-x86_64.exe" -Destination $dockerCompose

    # Scope Docker auth to this job: CI Identities for registry.ddbuild.io only,
    # no ECR catch-all that would fail without AWS_DEFAULT_REGION. Docker calls
    # `list` on the default credsStore (ecr-login) during compose init regardless
    # of which registries the Dockerfiles reference, so override the config here.
    $env:DOCKER_CONFIG = "$env:TEMP\docker-config-job"
    New-Item -ItemType Directory -Path $env:DOCKER_CONFIG -Force | Out-Null
    [IO.File]::WriteAllText(
        "$env:DOCKER_CONFIG\config.json",
        '{"credHelpers":{"registry.ddbuild.io":"ci-identities"}}'
    )

    cd dockerfiles\ci\windows

    docker version
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    & $dockerCompose version
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    foreach ($target in ($env:WINDOWS_IMAGE_TARGETS -split ' ')) {
      if ([string]::IsNullOrWhiteSpace($target)) { continue }

      # Pass CI_REGISTRY_IMAGE so the Dockerfile FROM (ARG default
      # datadog/dd-trace-ci) matches the registry.ddbuild.io image: push target.
      Write-Host "Building Windows CI image target $target..."
      & $dockerCompose build --pull --no-cache --build-arg CI_REGISTRY_IMAGE=$env:CI_REGISTRY_IMAGE $target
      if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      Write-Host "Pushing Windows CI image target $target..."
      & $dockerCompose push $target
      if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }

<?php /*
  Windows: single matrix over every compose service (base tools + tools + php).
  No needs/deps - like the Linux base/php builds, you manually run the base
  matrix entries before the dependent ones.
*/ ?>
Windows build:
  extends: .windows_image_build
  parallel:
    matrix:
      - WINDOWS_IMAGE_TARGETS:
<?php foreach (array_keys($winServices) as $svc): ?>
        - "<?= $svc ?>"
<?php endforeach; ?>

Windows publish:
  extends: .image_publish
  parallel:
    matrix:
      - TAG:
<?php foreach ($winServices as $tag): ?>
        - "<?= $tag ?>"
<?php endforeach; ?>
<?php foreach ($osList as ['name' => $os, 'dir' => $dir, 'services' => $services]): ?>
<?php /*
  One build job per PHP version. buildx bake reads the x-bake platforms from
  docker-compose.yml and builds both arches on the amd64 runner's "ci" builder,
  pushing a multi-arch manifest to the tag in the compose `image:` field.
*/ ?>

<?= $os ?> build:
  extends: .linux_image_build
  tags: ["arch:amd64"]
  parallel:
    matrix:
      - PHP_VERSION:
<?php foreach (array_keys($services) as $svc): ?>
          - <?= $svc, "\n" ?>
<?php endforeach; ?>
  script:
    - cd <?= $dir, "\n" ?>
    - docker buildx bake --no-cache --pull --push "${PHP_VERSION}"
<?php /*
  Mirror to Docker Hub: one matrix job per OS, independent (needs: [] via
  .image_publish) so it can sync existing images without rebuilding.
*/ ?>

<?= $os ?> publish:
  extends: .image_publish
  parallel:
    matrix:
      - TAG:
<?php foreach ($services as $tag): ?>
          - "<?= $tag ?>"
<?php endforeach; ?>
<?php endforeach; ?>
