.services:
  test-agent:
    name: registry.ddbuild.io/images/mirror/dd-apm-test-agent/ddapm-test-agent:v1.21.0
    alias: test-agent
    variables:
      LOG_LEVEL: DEBUG
      TRACE_LANGUAGE: php
      DD_TRACE_AGENT_URL: http://request-replayer:80
      PORT: 9126
      SNAPSHOT_DIR: /snapshots
      SNAPSHOT_CI: 1
      DD_SUPPRESS_TRACE_PARSE_ERRORS: true
      ENABLED_CHECKS: trace_stall,trace_peer_service,trace_dd_service
      DD_POOL_TRACE_CHECK_FAILURES: true
      DD_DISABLE_ERROR_RESPONSES: true

  request-replayer:
    name: registry.ddbuild.io/images/mirror/datadog/dd-trace-ci:php-request-replayer-2.0
    alias: request-replayer
    variables:
      DD_REQUEST_DUMPER_FILE: dump.json

  httpbin-integration:
    name: registry.ddbuild.io/images/mirror/kong/httpbin:0.2.2
    alias: httpbin-integration
