.services:
  test-agent:
    name: registry.ddbuild.io/images/mirror/dd-apm-test-agent/ddapm-test-agent:v1.20.0
    alias: test-agent
    variables:
      LOG_LEVEL: INFO
      SNAPSHOT_DIR: ${CI_PROJECT_DIR}/tests/snapshots
      SNAPSHOT_CI: 1
      PORT: 9126
      DD_POOL_TRACE_CHECK_FAILURES: true
      DD_DISABLE_ERROR_RESPONSES: true
      ENABLED_CHECKS: trace_content_length,trace_stall,meta_tracer_version_header,trace_count_header,trace_peer_service,trace_dd_service
