#!/usr/bin/env bash

set -e

TMP_DIR=.tmp
SOURCE_DIRS="src/DDTrace src/private bridge"
CLOC_EXCLUDE_FILE=tooling/metrics/.cloc-exclude-list

rm -rf ${TMP_DIR}
mkdir -p ${TMP_DIR}

php_lines="$(docker run --rm -v ${PWD}:/tmp aldanial/cloc --include-ext=php --exclude-list-file=${CLOC_EXCLUDE_FILE} ${SOURCE_DIRS} \
    | grep PHP \
    | rev \
    | cut -d' ' -f 1 \
    | rev)"
echo "Found ${php_lines} PHP lines."

# AGENT="DD_AGENT_HOST=request-replayer DD_TRACE_CLI_ENABLED=1"
# REQUEST_HOOK="DD_AGENT_HOST=request-replayer DD_TRACE_CLI_ENABLED=1"
# instructions_notracer="$(docker-compose --ansi always run --rm 7.4-buster bash -c 'for i in {1..2}; do valgrind --tool=callgrind php tooling/metrics/synthetic.php; done' \
#     | grep 'Collected :' \
#     | tail -1 \
#     | rev \
#     | cut -d' ' -f 1 \
#     | rev \
#     | sed 's/[^0-9]*//g')"
# echo "Instructions executed ${instructions_notracer} when notracer."

memory_notracer="$(docker-compose --ansi always run --rm 7.4-buster bash -c 'for i in {1..2}; do valgrind --tool=memcheck php tooling/metrics/synthetic.php; done' \
    | grep 'total heap usage' \
    | tail -1 \
    | sed -E 's/.*frees, ([0-9,]+) bytes allocated/\1/g' \
    | sed 's:,::g' \
    | sed 's/[^0-9]*//g')"
echo "Bytes allocated ${memory_notracer} when notracer."

# DD_AGENT_HOST=request-replayer DD_TRACE_CLI_ENABLED=1 valgrind --tool=callgrind  php -d ddtrace.request_init_hook=bridge/dd_wrap_autoloader.php tooling/metrics/synthetic.php

# DD_AGENT_HOST=request-replayer DD_TRACE_CLI_ENABLED=1 valgrind --tool=memcheck  php -d ddtrace.request_init_hook=bridge/dd_wrap_autoloader.php tooling/metrics/synthetic.php
