// Copyright 2021-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

// Hand-written prototypes for the V1 payload-builder FFI functions that are
// generated by declarative macros (`span_str_setter!`, `span_attr_setter!`,
// `event_attr_setter!`) in libdatadog's `datadog-sidecar-ffi/src/span_v1.rs`.
//
// cbindgen does not expand macro invocations, so these `#[no_mangle] pub extern
// "C"` symbols exist in the compiled library but are absent from the generated
// `components-rs/sidecar.h`. They are declared here so the tracer can call them.
// Keep in sync with the macro invocations in span_v1.rs; the non-macro V1 FFI
// (new_builder, intern_string, chunk/span/link/event constructors, id/parent/
// start/duration/error/kind setters, add_span_attr_bytes, ...) lives in the
// generated sidecar.h.

#ifndef DDOG_SIDECAR_V1_MACRO_FFI_H
#define DDOG_SIDECAR_V1_MACRO_FFI_H

#include <stdbool.h>
#include <stdint.h>

#include "common.h"

#ifdef __cplusplus
extern "C" {
#endif

// span_str_setter!: value is an interned string id (0 == empty).
void ddog_v1_set_span_service(struct ddog_TracerPayloadV1Builder *builder,
                              uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_name(struct ddog_TracerPayloadV1Builder *builder,
                           uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_resource(struct ddog_TracerPayloadV1Builder *builder,
                               uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_type(struct ddog_TracerPayloadV1Builder *builder,
                           uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_env(struct ddog_TracerPayloadV1Builder *builder,
                          uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_version(struct ddog_TracerPayloadV1Builder *builder,
                              uintptr_t chunk, uintptr_t span, uint32_t id);
void ddog_v1_set_span_component(struct ddog_TracerPayloadV1Builder *builder,
                                uintptr_t chunk, uintptr_t span, uint32_t id);

// span_attr_setter!: key_id is interned; value is interned id (str) or scalar.
void ddog_v1_add_span_attr_str(struct ddog_TracerPayloadV1Builder *builder,
                               uintptr_t chunk, uintptr_t span, uint32_t key_id, uint32_t value);
void ddog_v1_add_span_attr_int(struct ddog_TracerPayloadV1Builder *builder,
                               uintptr_t chunk, uintptr_t span, uint32_t key_id, int64_t value);
void ddog_v1_add_span_attr_double(struct ddog_TracerPayloadV1Builder *builder,
                                  uintptr_t chunk, uintptr_t span, uint32_t key_id, double value);
void ddog_v1_add_span_attr_bool(struct ddog_TracerPayloadV1Builder *builder,
                                uintptr_t chunk, uintptr_t span, uint32_t key_id, bool value);

// event_attr_setter!: key_id is interned; value is interned id (str) or scalar.
void ddog_v1_add_event_attr_str(struct ddog_TracerPayloadV1Builder *builder,
                                uintptr_t chunk, uintptr_t span, uintptr_t event,
                                uint32_t key_id, uint32_t value);
void ddog_v1_add_event_attr_int(struct ddog_TracerPayloadV1Builder *builder,
                                uintptr_t chunk, uintptr_t span, uintptr_t event,
                                uint32_t key_id, int64_t value);
void ddog_v1_add_event_attr_double(struct ddog_TracerPayloadV1Builder *builder,
                                   uintptr_t chunk, uintptr_t span, uintptr_t event,
                                   uint32_t key_id, double value);
void ddog_v1_add_event_attr_bool(struct ddog_TracerPayloadV1Builder *builder,
                                 uintptr_t chunk, uintptr_t span, uintptr_t event,
                                 uint32_t key_id, bool value);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // DDOG_SIDECAR_V1_MACRO_FFI_H
