<?php

return [
    __DIR__ . '/../src/api/Contracts/Tracer.php',
    __DIR__ . '/../src/api/Contracts/Span.php',
    __DIR__ . '/../src/api/Contracts/Scope.php',
    __DIR__ . '/../src/api/Contracts/ScopeManager.php',
    __DIR__ . '/../src/api/Contracts/SpanContext.php',
    __DIR__ . '/../src/api/Log/LoggingTrait.php',
    __DIR__ . '/../src/api/Data/SpanContext.php',
    __DIR__ . '/../src/api/Data/Span.php',
    __DIR__ . '/../src/api/Transport.php',
    __DIR__ . '/../src/api/Obfuscation/WildcardToRegex.php',
    __DIR__ . '/../src/api/Type.php',
    __DIR__ . '/../src/api/Tag.php',
    __DIR__ . '/../src/api/Reference.php',
    __DIR__ . '/../src/api/Exceptions/InvalidReferenceArgument.php',
    __DIR__ . '/../src/api/Exceptions/UnsupportedFormat.php',
    __DIR__ . '/../src/api/Exceptions/InvalidSpanArgument.php',
    __DIR__ . '/../src/api/Exceptions/InvalidReferencesSet.php',
    __DIR__ . '/../src/api/Exceptions/InvalidSpanOption.php',
    __DIR__ . '/../src/api/GlobalTracer.php',
    __DIR__ . '/../src/api/Http/Urls.php',
    __DIR__ . '/../src/api/Log/LoggerInterface.php',
    __DIR__ . '/../src/api/Log/InterpolateTrait.php',
    __DIR__ . '/../src/api/Log/LogLevel.php',
    __DIR__ . '/../src/api/Log/AbstractLogger.php',
    __DIR__ . '/../src/api/Log/ErrorLogLogger.php',
    __DIR__ . '/../src/api/Log/NullLogger.php',
    __DIR__ . '/../src/api/Format.php',
    __DIR__ . '/../src/api/StartSpanOptions.php',
];
