#!/usr/bin/env bash

php -r "(new PDO('mysql:host=mysql_integration', 'test', 'test'))->exec('CREATE DATABASE IF NOT EXISTS magento23');"

php -d memory_limit=1G ./bin/magento setup:install \
    --base-url=http://localhost/ \
    --backend-frontname=admin \
     --language=en_US \
     --timezone=America/Los_Angeles \
     --currency=USD \
     --db-host=mysql_integration \
     --db-name=magento23 \
     --db-user=test \
     --db-password=test \
     --use-secure=0 \
     --base-url-secure=0 \
     --use-secure-admin=0 \
     --admin-firstname=Admin \
     --admin-lastname=Admin \
     --admin-email=admin@admin.com \
     --admin-user=admin \
     --admin-password=Magento2 \
     --cleanup-database
