/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/profile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/profile.pb-c.h"
void   perftools__profiles__profile__init
                     (Perftools__Profiles__Profile         *message)
{
  static const Perftools__Profiles__Profile init_value = PERFTOOLS__PROFILES__PROFILE__INIT;
  *message = init_value;
}
size_t perftools__profiles__profile__get_packed_size
                     (const Perftools__Profiles__Profile *message)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__profile__pack
                     (const Perftools__Profiles__Profile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__profile__pack_to_buffer
                     (const Perftools__Profiles__Profile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Profile *
       perftools__profiles__profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Profile *)
     protobuf_c_message_unpack (&perftools__profiles__profile__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__profile__free_unpacked
                     (Perftools__Profiles__Profile *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__profile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__value_type__init
                     (Perftools__Profiles__ValueType         *message)
{
  static const Perftools__Profiles__ValueType init_value = PERFTOOLS__PROFILES__VALUE_TYPE__INIT;
  *message = init_value;
}
size_t perftools__profiles__value_type__get_packed_size
                     (const Perftools__Profiles__ValueType *message)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__value_type__pack
                     (const Perftools__Profiles__ValueType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__value_type__pack_to_buffer
                     (const Perftools__Profiles__ValueType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__ValueType *
       perftools__profiles__value_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__ValueType *)
     protobuf_c_message_unpack (&perftools__profiles__value_type__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__value_type__free_unpacked
                     (Perftools__Profiles__ValueType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__value_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__sample__init
                     (Perftools__Profiles__Sample         *message)
{
  static const Perftools__Profiles__Sample init_value = PERFTOOLS__PROFILES__SAMPLE__INIT;
  *message = init_value;
}
size_t perftools__profiles__sample__get_packed_size
                     (const Perftools__Profiles__Sample *message)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__sample__pack
                     (const Perftools__Profiles__Sample *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__sample__pack_to_buffer
                     (const Perftools__Profiles__Sample *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Sample *
       perftools__profiles__sample__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Sample *)
     protobuf_c_message_unpack (&perftools__profiles__sample__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__sample__free_unpacked
                     (Perftools__Profiles__Sample *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__sample__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__label__init
                     (Perftools__Profiles__Label         *message)
{
  static const Perftools__Profiles__Label init_value = PERFTOOLS__PROFILES__LABEL__INIT;
  *message = init_value;
}
size_t perftools__profiles__label__get_packed_size
                     (const Perftools__Profiles__Label *message)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__label__pack
                     (const Perftools__Profiles__Label *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__label__pack_to_buffer
                     (const Perftools__Profiles__Label *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Label *
       perftools__profiles__label__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Label *)
     protobuf_c_message_unpack (&perftools__profiles__label__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__label__free_unpacked
                     (Perftools__Profiles__Label *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__label__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__mapping__init
                     (Perftools__Profiles__Mapping         *message)
{
  static const Perftools__Profiles__Mapping init_value = PERFTOOLS__PROFILES__MAPPING__INIT;
  *message = init_value;
}
size_t perftools__profiles__mapping__get_packed_size
                     (const Perftools__Profiles__Mapping *message)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__mapping__pack
                     (const Perftools__Profiles__Mapping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__mapping__pack_to_buffer
                     (const Perftools__Profiles__Mapping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Mapping *
       perftools__profiles__mapping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Mapping *)
     protobuf_c_message_unpack (&perftools__profiles__mapping__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__mapping__free_unpacked
                     (Perftools__Profiles__Mapping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__mapping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__location__init
                     (Perftools__Profiles__Location         *message)
{
  static const Perftools__Profiles__Location init_value = PERFTOOLS__PROFILES__LOCATION__INIT;
  *message = init_value;
}
size_t perftools__profiles__location__get_packed_size
                     (const Perftools__Profiles__Location *message)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__location__pack
                     (const Perftools__Profiles__Location *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__location__pack_to_buffer
                     (const Perftools__Profiles__Location *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Location *
       perftools__profiles__location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Location *)
     protobuf_c_message_unpack (&perftools__profiles__location__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__location__free_unpacked
                     (Perftools__Profiles__Location *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__location__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__line__init
                     (Perftools__Profiles__Line         *message)
{
  static const Perftools__Profiles__Line init_value = PERFTOOLS__PROFILES__LINE__INIT;
  *message = init_value;
}
size_t perftools__profiles__line__get_packed_size
                     (const Perftools__Profiles__Line *message)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__line__pack
                     (const Perftools__Profiles__Line *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__line__pack_to_buffer
                     (const Perftools__Profiles__Line *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Line *
       perftools__profiles__line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Line *)
     protobuf_c_message_unpack (&perftools__profiles__line__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__line__free_unpacked
                     (Perftools__Profiles__Line *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perftools__profiles__function__init
                     (Perftools__Profiles__Function         *message)
{
  static const Perftools__Profiles__Function init_value = PERFTOOLS__PROFILES__FUNCTION__INIT;
  *message = init_value;
}
size_t perftools__profiles__function__get_packed_size
                     (const Perftools__Profiles__Function *message)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perftools__profiles__function__pack
                     (const Perftools__Profiles__Function *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perftools__profiles__function__pack_to_buffer
                     (const Perftools__Profiles__Function *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perftools__Profiles__Function *
       perftools__profiles__function__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perftools__Profiles__Function *)
     protobuf_c_message_unpack (&perftools__profiles__function__descriptor,
                                allocator, len, data);
}
void   perftools__profiles__function__free_unpacked
                     (Perftools__Profiles__Function *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perftools__profiles__function__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor perftools__profiles__profile__field_descriptors[14] =
{
  {
    "sample_type",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_sample_type),
    offsetof(Perftools__Profiles__Profile, sample_type),
    &perftools__profiles__value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_sample),
    offsetof(Perftools__Profiles__Profile, sample),
    &perftools__profiles__sample__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_mapping),
    offsetof(Perftools__Profiles__Profile, mapping),
    &perftools__profiles__mapping__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_location),
    offsetof(Perftools__Profiles__Profile, location),
    &perftools__profiles__location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Profile, n_function),
    offsetof(Perftools__Profiles__Profile, function),
    &perftools__profiles__function__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_table",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Perftools__Profiles__Profile, n_string_table),
    offsetof(Perftools__Profiles__Profile, string_table),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_frames",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, drop_frames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_frames",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, keep_frames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_nanos",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, time_nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration_nanos",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, duration_nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period_type",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, period_type),
    &perftools__profiles__value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Profile, n_comment),
    offsetof(Perftools__Profiles__Profile, comment),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_sample_type",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Profile, default_sample_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__profile__field_indices_by_name[] = {
  12,   /* field[12] = comment */
  13,   /* field[13] = default_sample_type */
  6,   /* field[6] = drop_frames */
  9,   /* field[9] = duration_nanos */
  4,   /* field[4] = function */
  7,   /* field[7] = keep_frames */
  3,   /* field[3] = location */
  2,   /* field[2] = mapping */
  11,   /* field[11] = period */
  10,   /* field[10] = period_type */
  1,   /* field[1] = sample */
  0,   /* field[0] = sample_type */
  5,   /* field[5] = string_table */
  8,   /* field[8] = time_nanos */
};
static const ProtobufCIntRange perftools__profiles__profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor perftools__profiles__profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Profile",
  "Profile",
  "Perftools__Profiles__Profile",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Profile),
  14,
  perftools__profiles__profile__field_descriptors,
  perftools__profiles__profile__field_indices_by_name,
  1,  perftools__profiles__profile__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__value_type__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__ValueType, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__ValueType, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__value_type__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = unit */
};
static const ProtobufCIntRange perftools__profiles__value_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perftools__profiles__value_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.ValueType",
  "ValueType",
  "Perftools__Profiles__ValueType",
  "perftools.profiles",
  sizeof(Perftools__Profiles__ValueType),
  2,
  perftools__profiles__value_type__field_descriptors,
  perftools__profiles__value_type__field_indices_by_name,
  1,  perftools__profiles__value_type__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__value_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__sample__field_descriptors[3] =
{
  {
    "location_id",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Perftools__Profiles__Sample, n_location_id),
    offsetof(Perftools__Profiles__Sample, location_id),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Perftools__Profiles__Sample, n_value),
    offsetof(Perftools__Profiles__Sample, value),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "label",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Sample, n_label),
    offsetof(Perftools__Profiles__Sample, label),
    &perftools__profiles__label__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__sample__field_indices_by_name[] = {
  2,   /* field[2] = label */
  0,   /* field[0] = location_id */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange perftools__profiles__sample__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perftools__profiles__sample__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Sample",
  "Sample",
  "Perftools__Profiles__Sample",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Sample),
  3,
  perftools__profiles__sample__field_descriptors,
  perftools__profiles__sample__field_indices_by_name,
  1,  perftools__profiles__sample__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__sample__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__label__field_descriptors[4] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Label, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Label, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Label, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_unit",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Label, num_unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__label__field_indices_by_name[] = {
  0,   /* field[0] = key */
  2,   /* field[2] = num */
  3,   /* field[3] = num_unit */
  1,   /* field[1] = str */
};
static const ProtobufCIntRange perftools__profiles__label__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor perftools__profiles__label__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Label",
  "Label",
  "Perftools__Profiles__Label",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Label),
  4,
  perftools__profiles__label__field_descriptors,
  perftools__profiles__label__field_indices_by_name,
  1,  perftools__profiles__label__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__label__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__mapping__field_descriptors[10] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_start",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, memory_start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_limit",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, memory_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_offset",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, file_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, build_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_functions",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, has_functions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_filenames",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, has_filenames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_line_numbers",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, has_line_numbers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_inline_frames",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Mapping, has_inline_frames),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__mapping__field_indices_by_name[] = {
  5,   /* field[5] = build_id */
  3,   /* field[3] = file_offset */
  4,   /* field[4] = filename */
  7,   /* field[7] = has_filenames */
  6,   /* field[6] = has_functions */
  9,   /* field[9] = has_inline_frames */
  8,   /* field[8] = has_line_numbers */
  0,   /* field[0] = id */
  2,   /* field[2] = memory_limit */
  1,   /* field[1] = memory_start */
};
static const ProtobufCIntRange perftools__profiles__mapping__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor perftools__profiles__mapping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Mapping",
  "Mapping",
  "Perftools__Profiles__Mapping",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Mapping),
  10,
  perftools__profiles__mapping__field_descriptors,
  perftools__profiles__mapping__field_indices_by_name,
  1,  perftools__profiles__mapping__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__mapping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__location__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Location, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mapping_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Location, mapping_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Location, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perftools__Profiles__Location, n_line),
    offsetof(Perftools__Profiles__Location, line),
    &perftools__profiles__line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_folded",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Location, is_folded),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__location__field_indices_by_name[] = {
  2,   /* field[2] = address */
  0,   /* field[0] = id */
  4,   /* field[4] = is_folded */
  3,   /* field[3] = line */
  1,   /* field[1] = mapping_id */
};
static const ProtobufCIntRange perftools__profiles__location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perftools__profiles__location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Location",
  "Location",
  "Perftools__Profiles__Location",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Location),
  5,
  perftools__profiles__location__field_descriptors,
  perftools__profiles__location__field_indices_by_name,
  1,  perftools__profiles__location__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__line__field_descriptors[2] =
{
  {
    "function_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Line, function_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Line, line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__line__field_indices_by_name[] = {
  0,   /* field[0] = function_id */
  1,   /* field[1] = line */
};
static const ProtobufCIntRange perftools__profiles__line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perftools__profiles__line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Line",
  "Line",
  "Perftools__Profiles__Line",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Line),
  2,
  perftools__profiles__line__field_descriptors,
  perftools__profiles__line__field_indices_by_name,
  1,  perftools__profiles__line__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perftools__profiles__function__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, system_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, filename),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_line",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perftools__Profiles__Function, start_line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perftools__profiles__function__field_indices_by_name[] = {
  3,   /* field[3] = filename */
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  4,   /* field[4] = start_line */
  2,   /* field[2] = system_name */
};
static const ProtobufCIntRange perftools__profiles__function__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perftools__profiles__function__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perftools.profiles.Function",
  "Function",
  "Perftools__Profiles__Function",
  "perftools.profiles",
  sizeof(Perftools__Profiles__Function),
  5,
  perftools__profiles__function__field_descriptors,
  perftools__profiles__function__field_indices_by_name,
  1,  perftools__profiles__function__number_ranges,
  (ProtobufCMessageInit) perftools__profiles__function__init,
  NULL,NULL,NULL    /* reserved[123] */
};
