services:

  request-replayer:
    image: ${CI_REGISTRY_IMAGE:-datadog/dd-trace-ci}:php-request-replayer-$REQUEST_REPLAYER_NEXT_VERSION
    build:
      context: request-replayer
      dockerfile: linux.Dockerfile
      x-bake:
        platforms:
          - linux/arm64
          - linux/amd64
