7.3.build:
	@docker build -t registry.ddbuild.io/apm-integrations-testing/handmade/php-wp5:7.3 .

7.3.shell: 7.3.build
	@docker run --rm -ti registry.ddbuild.io/apm-integrations-testing/handmade/php-wp5:7.3 bash
