issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-php:ref:refs/heads/master

claim_pattern:
  event_name: (workflow_dispatch|schedule)
  ref: refs/heads/master
  ref_protected: "true"
  job_workflow_ref: DataDog/dd-trace-php/.github/workflows/update_latest_versions.yml@refs/heads/master

permissions:
  contents: write
  pull_requests: write
