set(CMAKE_EXE_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libasan")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libasan")
set(CMAKE_C_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libasan")
set(CMAKE_CXX_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libasan")
set(CMAKE_SHARED_LINKER_FLAGS "--coverage")
set(CMAKE_MODULE_LINKER_FLAGS "--coverage")
set(CMAKE_EXE_LINKER_FLAGS "--coverage")
