if ((CMAKE_C_COMPILER_ID STREQUAL "Clang") OR ("${CMAKE_C_COMPILER_ID}" STREQUAL "AppleClang"))
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libsan")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer -shared-libsan")
else()
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer")
endif()
set(CMAKE_C_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer")
set(CMAKE_CXX_FLAGS_INIT "-fsanitize=address -fno-omit-frame-pointer")
