name: 'Test'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version'
        required: true
      trace_gnu_url:
        description: 'Url to the GNU trace bundle'
        required: true
      trace_musl_url:
        description: 'Url to the MUSL trace bundle'
        required: true
      profiling_url:
        description: 'Url to the profiling bundle'
        required: true
jobs:
  Build-Final-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: chmod a+x ${GITHUB_WORKSPACE}/.github/workflows/generate-final-artifact.sh
      - run: |
              ${GITHUB_WORKSPACE}/.github/workflows/generate-final-artifact.sh \
                ${{ github.event.inputs.version }} \
                ${{ github.event.inputs.trace_gnu_url }} \
                ${{ github.event.inputs.trace_musl_url }} \
                ${{ github.event.inputs.profiling_url }}
      - name: Archive GNU production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-linux-gnu.tar.gz
          path: dd-library-php-x86_64-linux-gnu.tar.gz
      - name: Archive musl production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dd-library-php-x86_64-linux-musl.tar.gz
          path: dd-library-php-x86_64-linux-musl.tar.gz
