name: Check snapshots

on:
  - pull_request

jobs:
  check-snapshots:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # need to add a comment to a PR

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '7.0.101'

      - name: "Check Snapshots"
        run: ./github-actions-helpers/build.sh SummaryOfSnapshotChanges
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
          TargetBranch: "${{ github.base_ref }}"
