name: Label PRs

on:
- pull_request

jobs:
  add-labels:

    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # Update labels on PRs (might not be necessary, but we call the UpdateIssue API so...)
      pull-requests: write # Update labels on PRs

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '7.0.101'

      - name: "Add labels"
        run: ./github-actions-helpers/build.sh AssignLabelsToPullRequest
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
