name: Auto add PR to vNext milestone

on:
  pull_request:
    branches:
      - master
      - main
    types: [closed]

jobs:
  add_to_milestone:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, '[Version Bump]') == false
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write # need to modify existing PR
      issues: write # need to potentially create a new milestone

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '7.0.101'

      - name: "Assign to vNext Milestone"
        run: ./github-actions-helpers/build.sh AssignPullRequestToMilestone
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
