name: Label PRs

on:
  - pull_request

jobs:
  add-labels:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # Update labels on PRs (might not be necessary, but we call the UpdateIssue API so...)
      pull-requests: write # Update labels on PRs
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: "7.0.101"

      - name: Get GitHub Token via dd-octo-sts
        id: generate-token
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/dd-trace-php
          policy: self.auto-label-prs

      - name: "Add labels"
        run: ./github-actions-helpers/build.sh AssignLabelsToPullRequest
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
