name: Label PRs

on:
- pull_request

jobs:
  add-labels:

    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write # Update labels on PRs (might not be necessary, but we call the UpdateIssue API so...)
      pull-requests: write # Update labels on PRs

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: '7.0.101'

      - name: "Add labels"
        run: ./github-actions-helpers/build.sh AssignLabelsToPullRequest
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
