name: Auto on rel published

on:
  release:
    types: [published]

jobs:
  trigger_aas_release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.101'

      - name: "Get version following release"
        id: versions
        run: ./tracer/build.sh OutputCurrentVersionToGitHub

      - name: "Close previous milestone"
        run: .\tracer\build.ps1 CloseMilestone
        env:
          Version: ${{steps.versions.outputs.version}}

