name: build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkitd.toml
      -
        name: Build
        uses: docker/bake-action@v1
        with:       
          targets: package-github
      - 
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildx
          path: build/package
          if-no-files-found: error