name: Update Latest Versions

on:
  workflow_dispatch: # can be triggered manually
  schedule:
    - cron: "30 6 * * 1" # weekly on Monday at 6:30 AM

jobs:
  update-latest-versions:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read
      id-token: write # Needed to federate tokens for dd-octo-sts

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        id: octo-sts
        with:
          scope: DataDog/dd-trace-php
          policy: self.update-latest-versions.create-pr

      - name: Install PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: "8.3"

      - name: Install PHP Tracer # Required by test bootstrap
        run: |
          curl -Lo /tmp/datadog-setup.php https://github.com/DataDog/dd-trace-php/releases/latest/download/datadog-setup.php
          sudo php /tmp/datadog-setup.php --php-bin=all
          rm /tmp/datadog-setup.php

      - name: Update Test Dependencies
        run: make composer_tests_update

      - name: Update Latest Versions
        run: php tests/PackageUpdater.php

      - name: Show changes
        run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          commit-message: "chore: update latest versions"
          title: "chore: update latest versions"
          branch: "update-latest-versions"
          base: "master"
          delete-branch: true
          body: This PR updates the latest pinned versions of the test dependencies.
